// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

// endregion ***************************** args.gotpl *****************************

// region    ************************** directives.gotpl **************************

// endregion ************************** directives.gotpl **************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _Feedback_id(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_id,
		func(ctx context.Context) (any, error) {
			return obj.ID, nil
		},
		nil,
		ec.marshalNID2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_id(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type ID does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_number(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_number,
		func(ctx context.Context) (any, error) {
			return obj.Number, nil
		},
		nil,
		ec.marshalNInt2int32,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_number(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type Int does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_targetType(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_targetType,
		func(ctx context.Context) (any, error) {
			return obj.TargetType, nil
		},
		nil,
		ec.marshalNFeedbackTargetType2chickᚋinternalᚋgraphqlᚐFeedbackTargetType,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_targetType(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type FeedbackTargetType does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_targetID(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_targetID,
		func(ctx context.Context) (any, error) {
			return obj.TargetID, nil
		},
		nil,
		ec.marshalNID2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_targetID(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type ID does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_authorID(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_authorID,
		func(ctx context.Context) (any, error) {
			return obj.AuthorID, nil
		},
		nil,
		ec.marshalNID2string,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_authorID(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type ID does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_rating(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_rating,
		func(ctx context.Context) (any, error) {
			return obj.Rating, nil
		},
		nil,
		ec.marshalNFeedbackRating2chickᚋinternalᚋgraphqlᚐFeedbackRating,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_rating(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type FeedbackRating does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_body(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_body,
		func(ctx context.Context) (any, error) {
			return obj.Body, nil
		},
		nil,
		ec.marshalOString2ᚖstring,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Feedback_body(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_createdAt(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_createdAt,
		func(ctx context.Context) (any, error) {
			return obj.CreatedAt, nil
		},
		nil,
		ec.marshalNTime2timeᚐTime,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_createdAt(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type Time does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Feedback_author(ctx context.Context, field graphql.CollectedField, obj *Feedback) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Feedback_author,
		func(ctx context.Context) (any, error) {
			return obj.Author, nil
		},
		nil,
		ec.marshalNAgent2ᚖchickᚋinternalᚋgraphqlᚐAgent,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Feedback_author(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Feedback",
		Field:      field,
		IsMethod:   false,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Agent_id(ctx, field)
			case "number":
				return ec.fieldContext_Agent_number(ctx, field)
			case "name":
				return ec.fieldContext_Agent_name(ctx, field)
			case "kind":
				return ec.fieldContext_Agent_kind(ctx, field)
			case "status":
				return ec.fieldContext_Agent_status(ctx, field)
			case "disabled":
				return ec.fieldContext_Agent_disabled(ctx, field)
			case "externalID":
				return ec.fieldContext_Agent_externalID(ctx, field)
			case "systemPrompt":
				return ec.fieldContext_Agent_systemPrompt(ctx, field)
			case "deviceInfo":
				return ec.fieldContext_Agent_deviceInfo(ctx, field)
			case "modelInfo":
				return ec.fieldContext_Agent_modelInfo(ctx, field)
			case "lastIP":
				return ec.fieldContext_Agent_lastIP(ctx, field)
			case "capabilities":
				return ec.fieldContext_Agent_capabilities(ctx, field)
			case "allowedCIDRs":
				return ec.fieldContext_Agent_allowedCIDRs(ctx, field)
			case "metadata":
				return ec.fieldContext_Agent_metadata(ctx, field)
			case "lastSeenAt":
				return ec.fieldContext_Agent_lastSeenAt(ctx, field)
			case "createdAt":
				return ec.fieldContext_Agent_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Agent_updatedAt(ctx, field)
			case "tokenPreview":
				return ec.fieldContext_Agent_tokenPreview(ctx, field)
			case "assignedIssues":
				return ec.fieldContext_Agent_assignedIssues(ctx, field)
			case "createdIssues":
				return ec.fieldContext_Agent_createdIssues(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Agent", field.Name)
		},
	}
	return fc, nil
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var feedbackImplementors = []string{"Feedback"}

func (ec *executionContext) _Feedback(ctx context.Context, sel ast.SelectionSet, obj *Feedback) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, feedbackImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("Feedback")
		case "id":
			out.Values[i] = ec._Feedback_id(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "number":
			out.Values[i] = ec._Feedback_number(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "targetType":
			out.Values[i] = ec._Feedback_targetType(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "targetID":
			out.Values[i] = ec._Feedback_targetID(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "authorID":
			out.Values[i] = ec._Feedback_authorID(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "rating":
			out.Values[i] = ec._Feedback_rating(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "body":
			out.Values[i] = ec._Feedback_body(ctx, field, obj)
		case "createdAt":
			out.Values[i] = ec._Feedback_createdAt(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "author":
			out.Values[i] = ec._Feedback_author(ctx, field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

func (ec *executionContext) marshalNFeedback2chickᚋinternalᚋgraphqlᚐFeedback(ctx context.Context, sel ast.SelectionSet, v Feedback) graphql.Marshaler {
	return ec._Feedback(ctx, sel, &v)
}

func (ec *executionContext) marshalNFeedback2ᚕᚖchickᚋinternalᚋgraphqlᚐFeedbackᚄ(ctx context.Context, sel ast.SelectionSet, v []*Feedback) graphql.Marshaler {
	ret := graphql.MarshalSliceConcurrently(ctx, len(v), 0, false, func(ctx context.Context, i int) graphql.Marshaler {
		fc := graphql.GetFieldContext(ctx)
		fc.Result = &v[i]
		return ec.marshalNFeedback2ᚖchickᚋinternalᚋgraphqlᚐFeedback(ctx, sel, v[i])
	})

	for _, e := range ret {
		if e == graphql.Null {
			return graphql.Null
		}
	}

	return ret
}

func (ec *executionContext) marshalNFeedback2ᚖchickᚋinternalᚋgraphqlᚐFeedback(ctx context.Context, sel ast.SelectionSet, v *Feedback) graphql.Marshaler {
	if v == nil {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
		return graphql.Null
	}
	return ec._Feedback(ctx, sel, v)
}

func (ec *executionContext) unmarshalNFeedbackRating2chickᚋinternalᚋgraphqlᚐFeedbackRating(ctx context.Context, v any) (FeedbackRating, error) {
	var res FeedbackRating
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNFeedbackRating2chickᚋinternalᚋgraphqlᚐFeedbackRating(ctx context.Context, sel ast.SelectionSet, v FeedbackRating) graphql.Marshaler {
	return v
}

func (ec *executionContext) unmarshalNFeedbackTargetType2chickᚋinternalᚋgraphqlᚐFeedbackTargetType(ctx context.Context, v any) (FeedbackTargetType, error) {
	var res FeedbackTargetType
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNFeedbackTargetType2chickᚋinternalᚋgraphqlᚐFeedbackTargetType(ctx context.Context, sel ast.SelectionSet, v FeedbackTargetType) graphql.Marshaler {
	return v
}

// endregion ***************************** type.gotpl *****************************
