package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"chick/internal/auth"
	"chick/internal/models"
	"chick/internal/service"
	"context"
	"errors"
	"fmt"
	"strconv"
	"time"
)

// RegisterAgent is the resolver for the registerAgent field.
func (r *mutationResolver) RegisterAgent(ctx context.Context, name string, kind AgentKind, externalID string, secret string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}
	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), externalID, secret, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	loginResult, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}
	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: loginResult.Token,
	}, nil
}

// LoginAgent is the resolver for the loginAgent field.
func (r *mutationResolver) LoginAgent(ctx context.Context, externalID string, secret string) (*LoginResult, error) {
	// Rate limit: 10 attempts per 15 minutes per IP
	ip := auth.ClientIPFromContext(ctx)
	if ip != "" && !r.LoginLimiter.Allow(ip) {
		return nil, fmt.Errorf("login: too many attempts, please try again later")
	}

	result, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("login: %w", err)
	}
	return &LoginResult{
		Agent: agentFromModel(result.Agent),
		Token: result.Token,
	}, nil
}

// UpdateAgentStatus is the resolver for the updateAgentStatus field.
func (r *mutationResolver) UpdateAgentStatus(ctx context.Context, id string, status AgentStatus) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.UpdateStatus(parseID(id), models.AgentStatus(status)); err != nil {
		return nil, fmt.Errorf("update agent status: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// UpdateAgentDisabled is the resolver for the updateAgentDisabled field.
func (r *mutationResolver) UpdateAgentDisabled(ctx context.Context, id string, disabled bool) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.SetDisabled(parseID(id), disabled); err != nil {
		return nil, fmt.Errorf("update agent disabled: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, id string, systemPrompt *string) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	sp := ""
	if systemPrompt != nil {
		sp = *systemPrompt
	}
	if err := r.AgentSvc.Update(parseID(id), sp); err != nil {
		return nil, fmt.Errorf("update agent: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// DeleteAgent is the resolver for the deleteAgent field.
func (r *mutationResolver) DeleteAgent(ctx context.Context, id string) (bool, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return false, err
	}
	if err := r.AgentSvc.Delete(parseID(id)); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateAgentAllowedCIDRs is the resolver for the updateAgentAllowedCIDRs field.
func (r *mutationResolver) UpdateAgentAllowedCIDRs(ctx context.Context, id string, allowedCIDRs []string) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.UpdateAllowedCIDRs(parseID(id), allowedCIDRs); err != nil {
		return nil, fmt.Errorf("update agent allowed CIDRs: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// CreateProjectAgent is the resolver for the createProjectAgent field.
func (r *mutationResolver) CreateProjectAgent(ctx context.Context, projectID string, name string, kind AgentKind, role *ProjectRole, externalID *string, secret *string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}

	// Auto-generate externalID if not provided
	extID := name
	if externalID != nil && *externalID != "" {
		extID = *externalID
	} else {
		extID = extID + "-" + randomHex(4)
	}

	// Auto-generate secret if not provided
	pw := ""
	if secret != nil && *secret != "" {
		pw = *secret
	} else {
		pw = randomHex(16)
	}

	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), extID, pw, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	projectRole := models.ProjectRoleMember
	if role != nil {
		projectRole = models.ProjectRole(*role)
	}
	if _, err := r.ProjectSvc.AddMember(pid, a.ID, projectRole); err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}

	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: a.Token,
	}, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, description *string) (*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	p, err := r.ProjectSvc.Create(name, desc)
	if err != nil {
		return nil, fmt.Errorf("create project: %w", err)
	}
	// Auto-add creator as project owner
	if _, err := r.ProjectSvc.AddMember(p.ID, agentID, models.ProjectRoleOwner); err != nil {
		return nil, fmt.Errorf("create project: add owner: %w", err)
	}
	return projectFromModel(p), nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, name *string, description *string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	n := ""
	if name != nil {
		n = *name
	}
	d := ""
	if description != nil {
		d = *description
	}
	p, err := r.ProjectSvc.Update(pid, n, d)
	if err != nil {
		return nil, fmt.Errorf("update project: %w", err)
	}
	return projectFromModel(p), nil
}

// UpdateProjectConfig is the resolver for the updateProjectConfig field.
func (r *mutationResolver) UpdateProjectConfig(ctx context.Context, id string, allowCreatorTransition *bool, requireCreatorCloseApproval *bool) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	p, err := r.ProjectSvc.UpdateConfig(pid, allowCreatorTransition, requireCreatorCloseApproval)
	if err != nil {
		return nil, fmt.Errorf("update project config: %w", err)
	}
	return projectFromModel(p), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.Delete(pid); err != nil {
		return false, fmt.Errorf("delete project: %w", err)
	}
	return true, nil
}

// AddProjectMember is the resolver for the addProjectMember field.
func (r *mutationResolver) AddProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.AddMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// UpdateProjectMember is the resolver for the updateProjectMember field.
func (r *mutationResolver) UpdateProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.UpdateMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("update project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, agentID string) (bool, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.RemoveMember(pid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove project member: %w", err)
	}
	return true, nil
}

// CreateIssue is the resolver for the createIssue field.
func (r *mutationResolver) CreateIssue(ctx context.Context, projectID string, title string, description *string, priority Priority, assigneeIDs []string, labelIDs []string, milestoneID *string, environment *string, branch *string, links []string) (*Issue, error) {
	pid := parseID(projectID)
	agentID, err := r.requireIssueProjectMemberByProject(ctx, pid)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	assigneeUintIDs := make([]uint, len(assigneeIDs))
	for i, id := range assigneeIDs {
		assigneeUintIDs[i] = parseID(id)
	}
	labelUintIDs := make([]uint, len(labelIDs))
	for i, id := range labelIDs {
		labelUintIDs[i] = parseID(id)
	}
	var mid *uint
	if milestoneID != nil && *milestoneID != "" {
		v := parseID(*milestoneID)
		mid = &v
	}
	issue, err := r.IssueSvc.Create(service.IssueCreateInput{ProjectID: pid, CreatorID: agentID, Title: title, Description: desc, Priority: models.Priority(priority), AssigneeIDs: assigneeUintIDs, LabelIDs: labelUintIDs, MilestoneID: mid, Environment: environment, Branch: branch, Link: linksToJson(links)})
	if err != nil {
		return nil, fmt.Errorf("create issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// UpdateIssue is the resolver for the updateIssue field.
func (r *mutationResolver) UpdateIssue(ctx context.Context, id string, title *string, description *string, priority *Priority, dueDate *time.Time, milestoneID *string, environment *string, branch *string, links []string, startedAt *time.Time, completedAt *time.Time, difficulty *int32) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	d := ""
	if description != nil {
		d = *description
	}
	p := models.Priority("")
	if priority != nil {
		p = models.Priority(*priority)
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	var mid *uint
	if milestoneID != nil {
		if *milestoneID != "" {
			v := parseID(*milestoneID)
			mid = &v
		} else {
			z := uint(0)
			mid = &z
		}
	}
	var diff *int
	if difficulty != nil {
		d := int(*difficulty)
		diff = &d
	}
	if links == nil {
		links = []string{}
	}
	issue, err := r.IssueSvc.Update(iid, service.IssueUpdateInput{
		Title:       &t,
		Description: &d,
		Priority:    &p,
		DueDate:     nt,
		MilestoneID: mid,
		Environment: environment,
		Branch:      branch,
		Link:        linksToJson(links),
		StartedAt:   startedAt,
		CompletedAt: completedAt,
		Difficulty:  diff,
	})
	if err != nil {
		return nil, fmt.Errorf("update issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// DeleteIssue is the resolver for the deleteIssue field.
func (r *mutationResolver) DeleteIssue(ctx context.Context, id string) (bool, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.Delete(iid); err != nil {
		return false, fmt.Errorf("delete issue: %w", err)
	}
	return true, nil
}

// TransitionIssue is the resolver for the transitionIssue field.
func (r *mutationResolver) TransitionIssue(ctx context.Context, id string, newState IssueState, actorID string, note *string) (*Issue, error) {
	iid := parseID(id)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(actorID) != agentID {
		return nil, errors.New("actorID 与认证身份不匹配")
	}
	issue, err := r.WorkflowSvc.Transition(iid, models.IssueState(newState), agentID, note)
	if err != nil {
		return nil, fmt.Errorf("transition issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// AddAssignee is the resolver for the addAssignee field.
func (r *mutationResolver) AddAssignee(ctx context.Context, issueID string, agentID string) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.AddAssignee(iid, parseID(agentID))
	if err != nil {
		return nil, fmt.Errorf("add assignee: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// RemoveAssignee is the resolver for the removeAssignee field.
func (r *mutationResolver) RemoveAssignee(ctx context.Context, issueID string, agentID string) (bool, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.RemoveAssignee(iid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove assignee: %w", err)
	}
	return true, nil
}

// UpdateAssigneeState is the resolver for the updateAssigneeState field.
func (r *mutationResolver) UpdateAssigneeState(ctx context.Context, issueID string, agentID string, state AssigneeState) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.UpdateAssigneeState(iid, parseID(agentID), models.AssigneeState(state))
	if err != nil {
		return nil, fmt.Errorf("update assignee state: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, issueID string, authorID string, body string, contentType CommentContentType, parentID *string) (*Comment, error) {
	iid := parseID(issueID)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	var pid *uint
	if parentID != nil {
		v := parseID(*parentID)
		pid = &v
	}
	c, err := r.CommentSvc.Create(iid, agentID, body, models.CommentContentType(contentType), pid)
	if err != nil {
		return nil, fmt.Errorf("add comment: %w", err)
	}
	return commentFromModel(c), nil
}

// AddProposalComment is the resolver for the addProposalComment field.
func (r *mutationResolver) AddProposalComment(ctx context.Context, proposalID string, authorID string, body string, contentType CommentContentType) (*Comment, error) {
	pid := parseID(proposalID)
	agentID, err := r.requireProposalProjectMember(ctx, pid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	c, err := r.CommentSvc.CreateForProposal(pid, agentID, body, models.CommentContentType(contentType), nil)
	if err != nil {
		return nil, fmt.Errorf("add proposal comment: %w", err)
	}
	return commentFromModel(c), nil
}

// AddTaskComment is the resolver for the addTaskComment field.
func (r *mutationResolver) AddTaskComment(ctx context.Context, taskID string, authorID string, body string, contentType CommentContentType) (*Comment, error) {
	tid := parseID(taskID)
	agentID, err := r.requireTaskProjectMember(ctx, tid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	c, err := r.CommentSvc.CreateForTask(tid, agentID, body, models.CommentContentType(contentType), nil)
	if err != nil {
		return nil, fmt.Errorf("add task comment: %w", err)
	}
	return commentFromModel(c), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, body string) (*Comment, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return nil, errors.New("只能编辑自己的评论")
	}
	c, err = r.CommentSvc.Update(parseID(id), body)
	if err != nil {
		return nil, fmt.Errorf("update comment: %w", err)
	}
	return commentFromModel(c), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return false, errors.New("只能删除自己的评论")
	}
	if err := r.CommentSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete comment: %w", err)
	}
	return true, nil
}

// AddLabels is the resolver for the addLabels field.
func (r *mutationResolver) AddLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.AddLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("add label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// RemoveLabels is the resolver for the removeLabels field.
func (r *mutationResolver) RemoveLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.RemoveLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("remove label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, projectID string, name string, color *string, capability *string, group *string) (*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	c := ""
	if color != nil {
		c = *color
	}
	cap := ""
	if capability != nil {
		cap = *capability
	}
	g := ""
	if group != nil {
		g = *group
	}
	l, err := r.ProjectSvc.CreateLabel(pid, name, c, cap, g)
	if err != nil {
		return nil, fmt.Errorf("create label: %w", err)
	}
	return labelFromModel(l), nil
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id string, name *string, color *string) (*Label, error) {
	label, err := r.ProjectSvc.GetLabelByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("标签不存在")
	}
	if _, err := r.requireProjectOwner(ctx, label.ProjectID); err != nil {
		return nil, err
	}
	n := ""
	if name != nil {
		n = *name
	}
	c := ""
	if color != nil {
		c = *color
	}
	l, err := r.ProjectSvc.UpdateLabel(parseID(id), n, c)
	if err != nil {
		return nil, fmt.Errorf("update label: %w", err)
	}
	return labelFromModel(l), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (bool, error) {
	label, err := r.ProjectSvc.GetLabelByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("标签不存在")
	}
	if _, err := r.requireProjectOwner(ctx, label.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteLabel(parseID(id)); err != nil {
		return false, fmt.Errorf("delete label: %w", err)
	}
	return true, nil
}

// CreateMilestone is the resolver for the createMilestone field.
func (r *mutationResolver) CreateMilestone(ctx context.Context, projectID string, title string, description *string, dueDate *time.Time) (*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	d := ""
	if description != nil {
		d = *description
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	m, err := r.ProjectSvc.CreateMilestone(pid, title, d, nt)
	if err != nil {
		return nil, fmt.Errorf("create milestone: %w", err)
	}
	return milestoneFromModel(m), nil
}

// UpdateMilestone is the resolver for the updateMilestone field.
func (r *mutationResolver) UpdateMilestone(ctx context.Context, id string, title *string, description *string, dueDate *time.Time, state *MilestoneState) (*Milestone, error) {
	milestone, err := r.ProjectSvc.GetMilestoneByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("里程碑不存在")
	}
	if _, err := r.requireProjectOwner(ctx, milestone.ProjectID); err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	d := ""
	if description != nil {
		d = *description
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	s := models.MilestoneState("")
	if state != nil {
		s = models.MilestoneState(*state)
	}
	m, err := r.ProjectSvc.UpdateMilestone(parseID(id), t, d, nt, s)
	if err != nil {
		return nil, fmt.Errorf("update milestone: %w", err)
	}
	return milestoneFromModel(m), nil
}

// DeleteMilestone is the resolver for the deleteMilestone field.
func (r *mutationResolver) DeleteMilestone(ctx context.Context, id string) (bool, error) {
	milestone, err := r.ProjectSvc.GetMilestoneByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("里程碑不存在")
	}
	if _, err := r.requireProjectOwner(ctx, milestone.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteMilestone(parseID(id)); err != nil {
		return false, fmt.Errorf("delete milestone: %w", err)
	}
	return true, nil
}

// CreateFeedback is the resolver for the createFeedback field.
func (r *mutationResolver) CreateFeedback(ctx context.Context, targetType FeedbackTargetType, targetID string, authorID string, rating FeedbackRating, body *string) (*Feedback, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	b := ""
	if body != nil {
		b = *body
	}
	f, err := r.FeedbackSvc.Create(models.FeedbackTargetType(targetType), parseID(targetID), agentID, feedbackRatingToInt(rating), b)
	if err != nil {
		return nil, fmt.Errorf("create feedback: %w", err)
	}
	return feedbackFromModel(f), nil
}

// CreateProposal is the resolver for the createProposal field.
func (r *mutationResolver) CreateProposal(ctx context.Context, projectID string, title string, description *string, priority Priority, labelIDs []string) (*Proposal, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	labelUintIDs := make([]uint, len(labelIDs))
	for i, id := range labelIDs {
		labelUintIDs[i] = parseID(id)
	}
	proposal, err := r.ProposalSvc.Create(pid, agentID, title, desc, models.Priority(priority), labelUintIDs)
	if err != nil {
		return nil, fmt.Errorf("create proposal: %w", err)
	}
	return proposalFromModel(proposal), nil
}

// UpdateProposal is the resolver for the updateProposal field.
func (r *mutationResolver) UpdateProposal(ctx context.Context, id string, title *string, description *string, priority *Priority) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	pid := parseID(id)
	changes := map[string]interface{}{}
	if title != nil {
		changes["title"] = *title
	}
	if description != nil {
		changes["description"] = *description
	}
	if priority != nil {
		changes["priority"] = string(*priority)
	}
	if err := r.ProposalSvc.Update(pid, changes); err != nil {
		return nil, fmt.Errorf("update proposal: %w", err)
	}
	p, err := r.ProposalSvc.GetByID(pid)
	if err != nil {
		return nil, err
	}
	return proposalFromModel(p), nil
}

// TransitionProposal is the resolver for the transitionProposal field.
func (r *mutationResolver) TransitionProposal(ctx context.Context, id string, newState ProposalState, actorID string, note *string) (*Proposal, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if parseID(actorID) != agentID {
		return nil, errors.New("actorID 与认证身份不匹配")
	}
	prop, err := r.ProposalSvc.TransitionState(parseID(id), models.ProposalState(newState), agentID, note)
	if err != nil {
		return nil, fmt.Errorf("transition proposal: %w", err)
	}
	return proposalFromModel(prop), nil
}

// ReviewProposal is the resolver for the reviewProposal field.
func (r *mutationResolver) ReviewProposal(ctx context.Context, id string, reviewerID string, approved bool, note *string) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	prop, err := r.ProposalSvc.Review(parseID(id), parseID(reviewerID), approved, note)
	if err != nil {
		return nil, fmt.Errorf("review proposal: %w", err)
	}
	return proposalFromModel(prop), nil
}

// DeleteProposal is the resolver for the deleteProposal field.
func (r *mutationResolver) DeleteProposal(ctx context.Context, id string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.ProposalSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete proposal: %w", err)
	}
	return true, nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, proposalID string, title string, description *string, priority *Priority, assigneeID *string) (*Task, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pid := parseID(proposalID)
	desc := ""
	if description != nil {
		desc = *description
	}
	prio := models.PriorityMedium
	if priority != nil {
		prio = models.Priority(*priority)
	}
	var aID *uint
	if assigneeID != nil && *assigneeID != "" {
		v := parseID(*assigneeID)
		aID = &v
	}
	proposal, err := r.ProposalSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	task, err := r.TaskSvc.Create(pid, proposal.ProjectID, agentID, title, desc, prio, aID)
	if err != nil {
		return nil, fmt.Errorf("create task: %w", err)
	}
	return taskFromModel(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, title *string, description *string, priority *Priority, state *TaskState) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	tid := parseID(id)
	changes := map[string]interface{}{}
	if title != nil {
		changes["title"] = *title
	}
	if description != nil {
		changes["description"] = *description
	}
	if priority != nil {
		changes["priority"] = string(*priority)
	}
	if state != nil {
		changes["state"] = string(*state)
	}
	if err := r.TaskSvc.Update(tid, changes); err != nil {
		return nil, fmt.Errorf("update task: %w", err)
	}
	t, err := r.TaskSvc.GetByID(tid)
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// AssignTask is the resolver for the assignTask field.
func (r *mutationResolver) AssignTask(ctx context.Context, id string, assigneeID string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.TaskSvc.Assign(parseID(id), parseID(assigneeID))
	if err != nil {
		return nil, fmt.Errorf("assign task: %w", err)
	}
	return taskFromModel(t), nil
}

// LinkIssuesToTask is the resolver for the linkIssuesToTask field.
func (r *mutationResolver) LinkIssuesToTask(ctx context.Context, taskID string, issueIDs []string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	tid := parseID(taskID)
	for _, iid := range issueIDs {
		if err := r.TaskSvc.LinkIssue(tid, parseID(iid)); err != nil {
			return nil, fmt.Errorf("link issue: %w", err)
		}
	}
	t, err := r.TaskSvc.GetByID(tid)
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// UnlinkIssueFromTask is the resolver for the unlinkIssueFromTask field.
func (r *mutationResolver) UnlinkIssueFromTask(ctx context.Context, taskID string, issueID string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	if err := r.TaskSvc.UnlinkIssue(parseID(taskID), parseID(issueID)); err != nil {
		return nil, fmt.Errorf("unlink issue: %w", err)
	}
	t, err := r.TaskSvc.GetByID(parseID(taskID))
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.TaskSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete task: %w", err)
	}
	return true, nil
}

// UpdateNotificationSetting is the resolver for the updateNotificationSetting field.
func (r *mutationResolver) UpdateNotificationSetting(ctx context.Context, agentID string, notificationType string, enabled bool, channel *string) (*NotificationSetting, error) {
	pid := parseID(agentID)
	ch := ""
	if channel != nil {
		ch = *channel
	}
	if err := r.NotifSvc.UpdateSetting(pid, notificationType, enabled, ch); err != nil {
		return nil, fmt.Errorf("update notification setting: %w", err)
	}

	// Read back the saved setting
	settings, err := r.NotifSvc.GetSettings(pid)
	if err != nil {
		return nil, fmt.Errorf("get notification settings: %w", err)
	}
	for _, s := range settings {
		if s.NotificationType == notificationType {
			return &NotificationSetting{
				ID:               strconv.FormatUint(uint64(s.ID), 10),
				AgentID:          strconv.FormatUint(uint64(s.AgentID), 10),
				NotificationType: s.NotificationType,
				Enabled:          s.Enabled,
				Channel:          s.Channel,
			}, nil
		}
	}

	return nil, fmt.Errorf("notification setting not found after update")
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (*NotificationEvent, error) {
	pid := parseID(id)
	if err := r.NotifSvc.MarkRead(pid); err != nil {
		return nil, fmt.Errorf("mark read: %w", err)
	}
	n, err := r.NotifSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get notification: %w", err)
	}
	return notificationToEvent(n), nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context, agentID string) (bool, error) {
	pid := parseID(agentID)
	if err := r.NotifSvc.MarkAllRead(pid); err != nil {
		return false, fmt.Errorf("mark all read: %w", err)
	}
	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
