package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"morning-glory/internal/models"
	"morning-glory/internal/notifications"
	"strconv"
)

// SupportedModels is the resolver for the supportedModels field.
func (r *queryResolver) SupportedModels(ctx context.Context) ([]string, error) {
	return models.SupportedModels, nil
}

// CommonDeviceInfo is the resolver for the commonDeviceInfo field.
func (r *queryResolver) CommonDeviceInfo(ctx context.Context) ([]string, error) {
	return models.CommonDeviceInfo, nil
}

// AllowHumanRegistration is the resolver for the allowHumanRegistration field.
func (r *queryResolver) AllowHumanRegistration(ctx context.Context) (bool, error) {
	return r.HumanReg, nil
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context, kind *AgentKind, status *AgentStatus, capabilities []string, projectID *string) ([]*Agent, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	filter := models.AgentFilter{}
	if kind != nil {
		k := models.AgentKind(*kind)
		filter.Kind = &k
	}
	if status != nil {
		s := models.AgentStatus(*status)
		filter.Status = &s
	}
	if projectID != nil {
		pid := parseID(*projectID)
		filter.ProjectID = &pid
	}
	if len(capabilities) > 0 {
		caps := make([]models.CapabilityType, len(capabilities))
		for i, c := range capabilities {
			caps[i] = models.CapabilityType(c)
		}
		filter.Capabilities = caps
	}
	agents, err := r.AgentSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list agents: %w", err)
	}
	result := make([]*Agent, len(agents))
	for i, a := range agents {
		result[i] = agentFromModel(&a)
	}
	return result, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context, id string) (*Agent, error) {
	if _, err := r.requireAgentAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return agentFromModel(a), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	projects, err := r.ProjectSvc.ListByAgent(agentID)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	result := make([]*Project, len(projects))
	for i, p := range projects {
		result[i] = projectFromModel(&p)
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	p, err := r.ProjectSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	return projectFromModel(p), nil
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, projectID string, group *string) ([]*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	g := ""
	if group != nil {
		g = *group
	}
	labels, err := r.ProjectSvc.ListLabels(pid, g)
	if err != nil {
		return nil, fmt.Errorf("list labels: %w", err)
	}
	result := make([]*Label, len(labels))
	for i, l := range labels {
		result[i] = labelFromModel(&l)
	}
	return result, nil
}

// Milestones is the resolver for the milestones field.
func (r *queryResolver) Milestones(ctx context.Context, projectID string, state *MilestoneState) ([]*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	s := models.MilestoneState("")
	if state != nil {
		s = models.MilestoneState(*state)
	}
	milestones, err := r.ProjectSvc.ListMilestones(pid, s)
	if err != nil {
		return nil, fmt.Errorf("list milestones: %w", err)
	}
	result := make([]*Milestone, len(milestones))
	for i, m := range milestones {
		result[i] = milestoneFromModel(&m)
	}
	return result, nil
}

// Issue is the resolver for the issue field.
func (r *queryResolver) Issue(ctx context.Context, id string) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, fmt.Errorf("get issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// Issues is the resolver for the issues field.
func (r *queryResolver) Issues(ctx context.Context, projectID string, state *IssueState, states []IssueState, priority *Priority, assigneeID *string, labelIDs []string, search *string, limit *int32, offset *int32) (*IssueConnection, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	filter := models.IssueFilter{ProjectID: uintPtr(pid)}
	if len(states) > 0 {
		filter.State = make([]models.IssueState, len(states))
		for i, s := range states {
			filter.State[i] = models.IssueState(s)
		}
	} else if state != nil {
		filter.State = []models.IssueState{models.IssueState(*state)}
	}
	if priority != nil {
		p := models.Priority(*priority)
		filter.Priority = &p
	}
	if assigneeID != nil {
		filter.AssigneeIDs = []uint{parseID(*assigneeID)}
	}
	if len(labelIDs) > 0 {
		ids := make([]uint, len(labelIDs))
		for i, lid := range labelIDs {
			ids[i] = parseID(lid)
		}
		filter.LabelIDs = ids
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}

	issues, total, err := r.IssueSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list issues: %w", err)
	}
	result := make([]*Issue, len(issues))
	for i, iss := range issues {
		result[i] = issueFromModel(&iss)
	}
	return &IssueConnection{
		Edges: result,
		Total: int32(total),
	}, nil
}

// Proposal is the resolver for the proposal field.
func (r *queryResolver) Proposal(ctx context.Context, id string) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	p, err := r.ProposalSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	return proposalFromModel(p), nil
}

// Proposals is the resolver for the proposals field.
func (r *queryResolver) Proposals(ctx context.Context, projectID string, state *ProposalState, priority *Priority, search *string, limit *int32, offset *int32) (*ProposalConnection, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	filter := models.ProposalFilter{ProjectID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.ProposalState{models.ProposalState(*state)}
	}
	if priority != nil {
		p := models.Priority(*priority)
		filter.Priority = &p
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}
	proposals, total, err := r.ProposalSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list proposals: %w", err)
	}
	result := make([]*Proposal, len(proposals))
	for i, p := range proposals {
		result[i] = proposalFromModel(&p)
	}
	return &ProposalConnection{Edges: result, Total: int32(total)}, nil
}

// ValidProposalTransitions is the resolver for the validProposalTransitions field.
func (r *queryResolver) ValidProposalTransitions(ctx context.Context, state ProposalState) ([]ProposalState, error) {
	states, err := r.ProposalSvc.ValidTransitions(models.ProposalState(state))
	if err != nil {
		return nil, fmt.Errorf("valid proposal transitions: %w", err)
	}
	result := make([]ProposalState, len(states))
	for i, s := range states {
		result[i] = ProposalState(s)
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.TaskSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get task: %w", err)
	}
	return taskFromModel(t), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, proposalID string, state *TaskState, assigneeID *string, search *string, limit *int32, offset *int32) (*TaskConnection, error) {
	pid := parseID(proposalID)
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	filter := models.TaskFilter{ProposalID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.TaskState{models.TaskState(*state)}
	}
	if assigneeID != nil && *assigneeID != "" {
		v := parseID(*assigneeID)
		filter.AssigneeID = &v
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}
	tasks, total, err := r.TaskSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list tasks: %w", err)
	}
	result := make([]*Task, len(tasks))
	for i, t := range tasks {
		result[i] = taskFromModel(&t)
	}
	return &TaskConnection{Edges: result, Total: int32(total)}, nil
}

// ValidTaskTransitions is the resolver for the validTaskTransitions field.
func (r *queryResolver) ValidTaskTransitions(ctx context.Context, state TaskState) ([]TaskState, error) {
	states, err := r.TaskSvc.ValidTransitions(models.TaskState(state))
	if err != nil {
		return nil, fmt.Errorf("valid task transitions: %w", err)
	}
	result := make([]TaskState, len(states))
	for i, s := range states {
		result[i] = TaskState(s)
	}
	return result, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, issueID *string, proposalID *string, taskID *string, orderBy *string) ([]*Comment, error) {
	asc := true
	if orderBy != nil && *orderBy == "desc" {
		asc = false
	}
	switch {
	case issueID != nil:
		iid := parseID(*issueID)
		if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
			return nil, err
		}
		comments, err := r.CommentSvc.ListByIssue(iid, asc)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	case proposalID != nil:
		pid := parseID(*proposalID)
		comments, err := r.CommentSvc.ListByProposal(pid, asc)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	case taskID != nil:
		tid := parseID(*taskID)
		comments, err := r.CommentSvc.ListByTask(tid, asc)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	default:
		return nil, errors.New("one of issueID, proposalID, or taskID is required")
	}
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, issueID *string, proposalID *string, taskID *string) ([]*TimelineEvent, error) {
	switch {
	case issueID != nil:
		iid := parseID(*issueID)
		if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
			return nil, err
		}
		events, err := r.IssueSvc.ListTimeline(iid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	case proposalID != nil:
		pid := parseID(*proposalID)
		events, err := r.ProposalSvc.ListTimeline(pid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	case taskID != nil:
		tid := parseID(*taskID)
		events, err := r.TaskSvc.ListTimeline(tid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	default:
		return nil, errors.New("one of issueID, proposalID, or taskID is required")
	}
}

// ValidTransitions is the resolver for the validTransitions field.
func (r *queryResolver) ValidTransitions(ctx context.Context, state IssueState) ([]IssueState, error) {
	states, err := r.WorkflowSvc.ValidTransitions(models.IssueState(state))
	if err != nil {
		return nil, fmt.Errorf("valid transitions: %w", err)
	}
	result := make([]IssueState, len(states))
	for i, s := range states {
		result[i] = IssueState(s)
	}
	return result, nil
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, targetType FeedbackTargetType, targetID string) ([]*Feedback, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	tid := parseID(targetID)
	switch targetType {
	case FeedbackTargetTypeIssue:
		if _, err := r.requireIssueProjectMember(ctx, tid); err != nil {
			return nil, err
		}
	case FeedbackTargetTypeAgent:
		if _, err := r.requireAgentAccess(ctx, tid); err != nil {
			return nil, err
		}
	case FeedbackTargetTypeAssignment:
		// Only the assigned agent can view assignment feedback
		if agentID != tid {
			return nil, errors.New("无权访问该 feedback")
		}
	case FeedbackTargetTypeComment:
		comment, err := r.CommentSvc.GetByID(tid)
		if err != nil {
			return nil, fmt.Errorf("comment not found")
		}
		if comment.IssueID != nil {
			if _, err := r.requireIssueProjectMember(ctx, parseID(formatID(*comment.IssueID))); err != nil {
				return nil, err
			}
		}
		list, err := r.FeedbackSvc.ListByTarget(models.FeedbackTargetType(targetType), tid)
		if err != nil {
			return nil, fmt.Errorf("list feedback: %w", err)
		}
		result := make([]*Feedback, len(list))
		for i, f := range list {
			result[i] = feedbackFromModel(&f)
		}
		return result, nil
	}
	return nil, errors.New("unknown target type")
}

// NotificationSettings is the resolver for the notificationSettings field.
func (r *queryResolver) NotificationSettings(ctx context.Context, agentID string) ([]*NotificationSetting, error) {
	pid := parseID(agentID)
	settings, err := r.NotifSvc.GetSettings(pid)
	if err != nil {
		return nil, fmt.Errorf("get notification settings: %w", err)
	}

	result := make([]*NotificationSetting, len(settings))
	for i, s := range settings {
		result[i] = &NotificationSetting{
			ID:               strconv.FormatUint(uint64(s.ID), 10),
			AgentID:          strconv.FormatUint(uint64(s.AgentID), 10),
			NotificationType: s.NotificationType,
			Enabled:          s.Enabled,
			Channel:          s.Channel,
		}
	}
	return result, nil
}

// NotificationTypes is the resolver for the notificationTypes field.
func (r *queryResolver) NotificationTypes(ctx context.Context) ([]*NotificationTypeInfo, error) {
	types := notifications.AllNotificationTypes()
	result := make([]*NotificationTypeInfo, len(types))
	for i, t := range types {
		result[i] = &NotificationTypeInfo{
			Type:        t["type"],
			Description: t["description"],
		}
	}
	return result, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, agentID string) ([]*NotificationEvent, error) {
	pid := parseID(agentID)
	notifs := r.NotifSvc.ListByAgent(pid)
	result := make([]*NotificationEvent, len(notifs))
	for i, n := range notifs {
		result[i] = notificationToEvent(n)
	}
	return result, nil
}

// Webhooks is the resolver for the webhooks field.
func (r *queryResolver) Webhooks(ctx context.Context, projectID string) ([]*Webhook, error) {
	pid := parseID(projectID)
	webhooks, err := r.WebhookSvc.ListByProject(pid)
	if err != nil {
		return nil, fmt.Errorf("list webhooks: %w", err)
	}
	result := make([]*Webhook, len(webhooks))
	for i, w := range webhooks {
		result[i] = webhookFromModel(&w)
	}
	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
