// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/vektah/gqlparser/v2/ast"
)

// region    ************************** generated!.gotpl **************************

type QueryResolver interface {
	SupportedModels(ctx context.Context) ([]string, error)
	CommonDeviceInfo(ctx context.Context) ([]string, error)
	AllowHumanRegistration(ctx context.Context) (bool, error)
	Agents(ctx context.Context, kind *AgentKind, status *AgentStatus, capabilities []string, projectID *string) ([]*Agent, error)
	Agent(ctx context.Context, id string) (*Agent, error)
	Projects(ctx context.Context) ([]*Project, error)
	Project(ctx context.Context, id string) (*Project, error)
	Labels(ctx context.Context, projectID string, group *string) ([]*Label, error)
	Milestones(ctx context.Context, projectID string, state *MilestoneState) ([]*Milestone, error)
	Issue(ctx context.Context, id string) (*Issue, error)
	Issues(ctx context.Context, projectID string, state *IssueState, states []IssueState, priority *Priority, assigneeID *string, labelIDs []string, search *string, limit *int32, offset *int32) (*IssueConnection, error)
	Proposal(ctx context.Context, id string) (*Proposal, error)
	Proposals(ctx context.Context, projectID string, state *ProposalState, priority *Priority, search *string, limit *int32, offset *int32) (*ProposalConnection, error)
	ValidProposalTransitions(ctx context.Context, state ProposalState) ([]ProposalState, error)
	Task(ctx context.Context, id string) (*Task, error)
	Tasks(ctx context.Context, proposalID string, state *TaskState, assigneeID *string, search *string, limit *int32, offset *int32) (*TaskConnection, error)
	ValidTaskTransitions(ctx context.Context, state TaskState) ([]TaskState, error)
	Comments(ctx context.Context, issueID *string, proposalID *string, taskID *string, orderBy *string) ([]*Comment, error)
	Timeline(ctx context.Context, issueID *string, proposalID *string, taskID *string) ([]*TimelineEvent, error)
	ValidTransitions(ctx context.Context, state IssueState) ([]IssueState, error)
	Feedback(ctx context.Context, targetType FeedbackTargetType, targetID string) ([]*Feedback, error)
	NotificationSettings(ctx context.Context, agentID string) ([]*NotificationSetting, error)
	NotificationTypes(ctx context.Context) ([]*NotificationTypeInfo, error)
	Notifications(ctx context.Context, agentID string) ([]*NotificationEvent, error)
	Webhooks(ctx context.Context, projectID string) ([]*Webhook, error)
}

// endregion ************************** generated!.gotpl **************************

// region    ***************************** args.gotpl *****************************

func (ec *executionContext) field_Query___type_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "name", ec.unmarshalNString2string)
	if err != nil {
		return nil, err
	}
	args["name"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_agent_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_agents_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "kind", ec.unmarshalOAgentKind2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐAgentKind)
	if err != nil {
		return nil, err
	}
	args["kind"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "status", ec.unmarshalOAgentStatus2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐAgentStatus)
	if err != nil {
		return nil, err
	}
	args["status"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "capabilities", ec.unmarshalOString2ᚕstringᚄ)
	if err != nil {
		return nil, err
	}
	args["capabilities"] = arg2
	arg3, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg3
	return args, nil
}

func (ec *executionContext) field_Query_comments_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "issueID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["issueID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "proposalID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["proposalID"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "taskID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["taskID"] = arg2
	arg3, err := graphql.ProcessArgField(ctx, rawArgs, "orderBy", ec.unmarshalOString2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["orderBy"] = arg3
	return args, nil
}

func (ec *executionContext) field_Query_feedback_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "targetType", ec.unmarshalNFeedbackTargetType2morningᚑgloryᚋinternalᚋgraphqlᚐFeedbackTargetType)
	if err != nil {
		return nil, err
	}
	args["targetType"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "targetID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["targetID"] = arg1
	return args, nil
}

func (ec *executionContext) field_Query_issue_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_issues_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalOIssueState2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐIssueState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "states", ec.unmarshalOIssueState2ᚕmorningᚑgloryᚋinternalᚋgraphqlᚐIssueStateᚄ)
	if err != nil {
		return nil, err
	}
	args["states"] = arg2
	arg3, err := graphql.ProcessArgField(ctx, rawArgs, "priority", ec.unmarshalOPriority2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐPriority)
	if err != nil {
		return nil, err
	}
	args["priority"] = arg3
	arg4, err := graphql.ProcessArgField(ctx, rawArgs, "assigneeID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["assigneeID"] = arg4
	arg5, err := graphql.ProcessArgField(ctx, rawArgs, "labelIDs", ec.unmarshalOID2ᚕstringᚄ)
	if err != nil {
		return nil, err
	}
	args["labelIDs"] = arg5
	arg6, err := graphql.ProcessArgField(ctx, rawArgs, "search", ec.unmarshalOString2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["search"] = arg6
	arg7, err := graphql.ProcessArgField(ctx, rawArgs, "limit", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["limit"] = arg7
	arg8, err := graphql.ProcessArgField(ctx, rawArgs, "offset", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["offset"] = arg8
	return args, nil
}

func (ec *executionContext) field_Query_labels_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "group", ec.unmarshalOString2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["group"] = arg1
	return args, nil
}

func (ec *executionContext) field_Query_milestones_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalOMilestoneState2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐMilestoneState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg1
	return args, nil
}

func (ec *executionContext) field_Query_notificationSettings_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "agentID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["agentID"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_notifications_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "agentID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["agentID"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_project_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_proposal_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_proposals_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalOProposalState2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐProposalState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "priority", ec.unmarshalOPriority2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐPriority)
	if err != nil {
		return nil, err
	}
	args["priority"] = arg2
	arg3, err := graphql.ProcessArgField(ctx, rawArgs, "search", ec.unmarshalOString2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["search"] = arg3
	arg4, err := graphql.ProcessArgField(ctx, rawArgs, "limit", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["limit"] = arg4
	arg5, err := graphql.ProcessArgField(ctx, rawArgs, "offset", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["offset"] = arg5
	return args, nil
}

func (ec *executionContext) field_Query_task_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "id", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["id"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_tasks_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "proposalID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["proposalID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalOTaskState2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐTaskState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "assigneeID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["assigneeID"] = arg2
	arg3, err := graphql.ProcessArgField(ctx, rawArgs, "search", ec.unmarshalOString2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["search"] = arg3
	arg4, err := graphql.ProcessArgField(ctx, rawArgs, "limit", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["limit"] = arg4
	arg5, err := graphql.ProcessArgField(ctx, rawArgs, "offset", ec.unmarshalOInt2ᚖint32)
	if err != nil {
		return nil, err
	}
	args["offset"] = arg5
	return args, nil
}

func (ec *executionContext) field_Query_timeline_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "issueID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["issueID"] = arg0
	arg1, err := graphql.ProcessArgField(ctx, rawArgs, "proposalID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["proposalID"] = arg1
	arg2, err := graphql.ProcessArgField(ctx, rawArgs, "taskID", ec.unmarshalOID2ᚖstring)
	if err != nil {
		return nil, err
	}
	args["taskID"] = arg2
	return args, nil
}

func (ec *executionContext) field_Query_validProposalTransitions_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalNProposalState2morningᚑgloryᚋinternalᚋgraphqlᚐProposalState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_validTaskTransitions_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalNTaskState2morningᚑgloryᚋinternalᚋgraphqlᚐTaskState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_validTransitions_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "state", ec.unmarshalNIssueState2morningᚑgloryᚋinternalᚋgraphqlᚐIssueState)
	if err != nil {
		return nil, err
	}
	args["state"] = arg0
	return args, nil
}

func (ec *executionContext) field_Query_webhooks_args(ctx context.Context, rawArgs map[string]any) (map[string]any, error) {
	var err error
	args := map[string]any{}
	arg0, err := graphql.ProcessArgField(ctx, rawArgs, "projectID", ec.unmarshalNID2string)
	if err != nil {
		return nil, err
	}
	args["projectID"] = arg0
	return args, nil
}

// endregion ***************************** args.gotpl *****************************

// region    ************************** directives.gotpl **************************

// endregion ************************** directives.gotpl **************************

// region    **************************** field.gotpl *****************************

func (ec *executionContext) _Query_supportedModels(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_supportedModels,
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Query().SupportedModels(ctx)
		},
		nil,
		ec.marshalNString2ᚕstringᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_supportedModels(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Query_commonDeviceInfo(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_commonDeviceInfo,
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Query().CommonDeviceInfo(ctx)
		},
		nil,
		ec.marshalNString2ᚕstringᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_commonDeviceInfo(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type String does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Query_allowHumanRegistration(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_allowHumanRegistration,
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Query().AllowHumanRegistration(ctx)
		},
		nil,
		ec.marshalNBoolean2bool,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_allowHumanRegistration(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type Boolean does not have child fields")
		},
	}
	return fc, nil
}

func (ec *executionContext) _Query_agents(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_agents,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Agents(ctx, fc.Args["kind"].(*AgentKind), fc.Args["status"].(*AgentStatus), fc.Args["capabilities"].([]string), fc.Args["projectID"].(*string))
		},
		nil,
		ec.marshalNAgent2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐAgentᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_agents(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Agent_id(ctx, field)
			case "number":
				return ec.fieldContext_Agent_number(ctx, field)
			case "name":
				return ec.fieldContext_Agent_name(ctx, field)
			case "kind":
				return ec.fieldContext_Agent_kind(ctx, field)
			case "status":
				return ec.fieldContext_Agent_status(ctx, field)
			case "disabled":
				return ec.fieldContext_Agent_disabled(ctx, field)
			case "externalID":
				return ec.fieldContext_Agent_externalID(ctx, field)
			case "systemPrompt":
				return ec.fieldContext_Agent_systemPrompt(ctx, field)
			case "deviceInfo":
				return ec.fieldContext_Agent_deviceInfo(ctx, field)
			case "modelInfo":
				return ec.fieldContext_Agent_modelInfo(ctx, field)
			case "lastIP":
				return ec.fieldContext_Agent_lastIP(ctx, field)
			case "capabilities":
				return ec.fieldContext_Agent_capabilities(ctx, field)
			case "allowedCIDRs":
				return ec.fieldContext_Agent_allowedCIDRs(ctx, field)
			case "metadata":
				return ec.fieldContext_Agent_metadata(ctx, field)
			case "lastSeenAt":
				return ec.fieldContext_Agent_lastSeenAt(ctx, field)
			case "createdAt":
				return ec.fieldContext_Agent_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Agent_updatedAt(ctx, field)
			case "tokenPreview":
				return ec.fieldContext_Agent_tokenPreview(ctx, field)
			case "assignedIssues":
				return ec.fieldContext_Agent_assignedIssues(ctx, field)
			case "createdIssues":
				return ec.fieldContext_Agent_createdIssues(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Agent", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_agents_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_agent(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_agent,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Agent(ctx, fc.Args["id"].(string))
		},
		nil,
		ec.marshalOAgent2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐAgent,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query_agent(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Agent_id(ctx, field)
			case "number":
				return ec.fieldContext_Agent_number(ctx, field)
			case "name":
				return ec.fieldContext_Agent_name(ctx, field)
			case "kind":
				return ec.fieldContext_Agent_kind(ctx, field)
			case "status":
				return ec.fieldContext_Agent_status(ctx, field)
			case "disabled":
				return ec.fieldContext_Agent_disabled(ctx, field)
			case "externalID":
				return ec.fieldContext_Agent_externalID(ctx, field)
			case "systemPrompt":
				return ec.fieldContext_Agent_systemPrompt(ctx, field)
			case "deviceInfo":
				return ec.fieldContext_Agent_deviceInfo(ctx, field)
			case "modelInfo":
				return ec.fieldContext_Agent_modelInfo(ctx, field)
			case "lastIP":
				return ec.fieldContext_Agent_lastIP(ctx, field)
			case "capabilities":
				return ec.fieldContext_Agent_capabilities(ctx, field)
			case "allowedCIDRs":
				return ec.fieldContext_Agent_allowedCIDRs(ctx, field)
			case "metadata":
				return ec.fieldContext_Agent_metadata(ctx, field)
			case "lastSeenAt":
				return ec.fieldContext_Agent_lastSeenAt(ctx, field)
			case "createdAt":
				return ec.fieldContext_Agent_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Agent_updatedAt(ctx, field)
			case "tokenPreview":
				return ec.fieldContext_Agent_tokenPreview(ctx, field)
			case "assignedIssues":
				return ec.fieldContext_Agent_assignedIssues(ctx, field)
			case "createdIssues":
				return ec.fieldContext_Agent_createdIssues(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Agent", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_agent_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_projects(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_projects,
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Query().Projects(ctx)
		},
		nil,
		ec.marshalNProject2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐProjectᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_projects(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Project_id(ctx, field)
			case "number":
				return ec.fieldContext_Project_number(ctx, field)
			case "name":
				return ec.fieldContext_Project_name(ctx, field)
			case "description":
				return ec.fieldContext_Project_description(ctx, field)
			case "allowCreatorTransition":
				return ec.fieldContext_Project_allowCreatorTransition(ctx, field)
			case "requireCreatorCloseApproval":
				return ec.fieldContext_Project_requireCreatorCloseApproval(ctx, field)
			case "createdAt":
				return ec.fieldContext_Project_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Project_updatedAt(ctx, field)
			case "members":
				return ec.fieldContext_Project_members(ctx, field)
			case "labels":
				return ec.fieldContext_Project_labels(ctx, field)
			case "milestones":
				return ec.fieldContext_Project_milestones(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Project", field.Name)
		},
	}
	return fc, nil
}

func (ec *executionContext) _Query_project(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_project,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Project(ctx, fc.Args["id"].(string))
		},
		nil,
		ec.marshalOProject2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐProject,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query_project(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Project_id(ctx, field)
			case "number":
				return ec.fieldContext_Project_number(ctx, field)
			case "name":
				return ec.fieldContext_Project_name(ctx, field)
			case "description":
				return ec.fieldContext_Project_description(ctx, field)
			case "allowCreatorTransition":
				return ec.fieldContext_Project_allowCreatorTransition(ctx, field)
			case "requireCreatorCloseApproval":
				return ec.fieldContext_Project_requireCreatorCloseApproval(ctx, field)
			case "createdAt":
				return ec.fieldContext_Project_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Project_updatedAt(ctx, field)
			case "members":
				return ec.fieldContext_Project_members(ctx, field)
			case "labels":
				return ec.fieldContext_Project_labels(ctx, field)
			case "milestones":
				return ec.fieldContext_Project_milestones(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Project", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_project_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_labels(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_labels,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Labels(ctx, fc.Args["projectID"].(string), fc.Args["group"].(*string))
		},
		nil,
		ec.marshalNLabel2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐLabelᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_labels(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Label_id(ctx, field)
			case "number":
				return ec.fieldContext_Label_number(ctx, field)
			case "name":
				return ec.fieldContext_Label_name(ctx, field)
			case "color":
				return ec.fieldContext_Label_color(ctx, field)
			case "description":
				return ec.fieldContext_Label_description(ctx, field)
			case "projectID":
				return ec.fieldContext_Label_projectID(ctx, field)
			case "capability":
				return ec.fieldContext_Label_capability(ctx, field)
			case "group":
				return ec.fieldContext_Label_group(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Label", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_labels_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_milestones(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_milestones,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Milestones(ctx, fc.Args["projectID"].(string), fc.Args["state"].(*MilestoneState))
		},
		nil,
		ec.marshalNMilestone2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐMilestoneᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_milestones(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Milestone_id(ctx, field)
			case "number":
				return ec.fieldContext_Milestone_number(ctx, field)
			case "projectID":
				return ec.fieldContext_Milestone_projectID(ctx, field)
			case "title":
				return ec.fieldContext_Milestone_title(ctx, field)
			case "description":
				return ec.fieldContext_Milestone_description(ctx, field)
			case "state":
				return ec.fieldContext_Milestone_state(ctx, field)
			case "dueDate":
				return ec.fieldContext_Milestone_dueDate(ctx, field)
			case "createdAt":
				return ec.fieldContext_Milestone_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Milestone_updatedAt(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Milestone", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_milestones_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_issue(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_issue,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Issue(ctx, fc.Args["id"].(string))
		},
		nil,
		ec.marshalOIssue2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐIssue,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query_issue(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Issue_id(ctx, field)
			case "number":
				return ec.fieldContext_Issue_number(ctx, field)
			case "projectID":
				return ec.fieldContext_Issue_projectID(ctx, field)
			case "title":
				return ec.fieldContext_Issue_title(ctx, field)
			case "description":
				return ec.fieldContext_Issue_description(ctx, field)
			case "state":
				return ec.fieldContext_Issue_state(ctx, field)
			case "priority":
				return ec.fieldContext_Issue_priority(ctx, field)
			case "creatorID":
				return ec.fieldContext_Issue_creatorID(ctx, field)
			case "parentID":
				return ec.fieldContext_Issue_parentID(ctx, field)
			case "dueDate":
				return ec.fieldContext_Issue_dueDate(ctx, field)
			case "environment":
				return ec.fieldContext_Issue_environment(ctx, field)
			case "branch":
				return ec.fieldContext_Issue_branch(ctx, field)
			case "links":
				return ec.fieldContext_Issue_links(ctx, field)
			case "commits":
				return ec.fieldContext_Issue_commits(ctx, field)
			case "fixedInCommit":
				return ec.fieldContext_Issue_fixedInCommit(ctx, field)
			case "solution":
				return ec.fieldContext_Issue_solution(ctx, field)
			case "rootCause":
				return ec.fieldContext_Issue_rootCause(ctx, field)
			case "closedAt":
				return ec.fieldContext_Issue_closedAt(ctx, field)
			case "startedAt":
				return ec.fieldContext_Issue_startedAt(ctx, field)
			case "completedAt":
				return ec.fieldContext_Issue_completedAt(ctx, field)
			case "difficulty":
				return ec.fieldContext_Issue_difficulty(ctx, field)
			case "createdAt":
				return ec.fieldContext_Issue_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Issue_updatedAt(ctx, field)
			case "creator":
				return ec.fieldContext_Issue_creator(ctx, field)
			case "assignees":
				return ec.fieldContext_Issue_assignees(ctx, field)
			case "labels":
				return ec.fieldContext_Issue_labels(ctx, field)
			case "children":
				return ec.fieldContext_Issue_children(ctx, field)
			case "milestone":
				return ec.fieldContext_Issue_milestone(ctx, field)
			case "structuredOutput":
				return ec.fieldContext_Issue_structuredOutput(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Issue", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_issue_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_issues(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_issues,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Issues(ctx, fc.Args["projectID"].(string), fc.Args["state"].(*IssueState), fc.Args["states"].([]IssueState), fc.Args["priority"].(*Priority), fc.Args["assigneeID"].(*string), fc.Args["labelIDs"].([]string), fc.Args["search"].(*string), fc.Args["limit"].(*int32), fc.Args["offset"].(*int32))
		},
		nil,
		ec.marshalNIssueConnection2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐIssueConnection,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_issues(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "edges":
				return ec.fieldContext_IssueConnection_edges(ctx, field)
			case "total":
				return ec.fieldContext_IssueConnection_total(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type IssueConnection", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_issues_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_proposal(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_proposal,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Proposal(ctx, fc.Args["id"].(string))
		},
		nil,
		ec.marshalOProposal2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐProposal,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query_proposal(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Proposal_id(ctx, field)
			case "number":
				return ec.fieldContext_Proposal_number(ctx, field)
			case "projectID":
				return ec.fieldContext_Proposal_projectID(ctx, field)
			case "title":
				return ec.fieldContext_Proposal_title(ctx, field)
			case "description":
				return ec.fieldContext_Proposal_description(ctx, field)
			case "state":
				return ec.fieldContext_Proposal_state(ctx, field)
			case "priority":
				return ec.fieldContext_Proposal_priority(ctx, field)
			case "authorID":
				return ec.fieldContext_Proposal_authorID(ctx, field)
			case "reviewerID":
				return ec.fieldContext_Proposal_reviewerID(ctx, field)
			case "reviewNote":
				return ec.fieldContext_Proposal_reviewNote(ctx, field)
			case "reviewedAt":
				return ec.fieldContext_Proposal_reviewedAt(ctx, field)
			case "submittedAt":
				return ec.fieldContext_Proposal_submittedAt(ctx, field)
			case "approvedAt":
				return ec.fieldContext_Proposal_approvedAt(ctx, field)
			case "startedAt":
				return ec.fieldContext_Proposal_startedAt(ctx, field)
			case "completedAt":
				return ec.fieldContext_Proposal_completedAt(ctx, field)
			case "cancelledAt":
				return ec.fieldContext_Proposal_cancelledAt(ctx, field)
			case "createdAt":
				return ec.fieldContext_Proposal_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Proposal_updatedAt(ctx, field)
			case "author":
				return ec.fieldContext_Proposal_author(ctx, field)
			case "reviewer":
				return ec.fieldContext_Proposal_reviewer(ctx, field)
			case "labels":
				return ec.fieldContext_Proposal_labels(ctx, field)
			case "tasks":
				return ec.fieldContext_Proposal_tasks(ctx, field)
			case "comments":
				return ec.fieldContext_Proposal_comments(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Proposal", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_proposal_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_proposals(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_proposals,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Proposals(ctx, fc.Args["projectID"].(string), fc.Args["state"].(*ProposalState), fc.Args["priority"].(*Priority), fc.Args["search"].(*string), fc.Args["limit"].(*int32), fc.Args["offset"].(*int32))
		},
		nil,
		ec.marshalNProposalConnection2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐProposalConnection,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_proposals(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "edges":
				return ec.fieldContext_ProposalConnection_edges(ctx, field)
			case "total":
				return ec.fieldContext_ProposalConnection_total(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type ProposalConnection", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_proposals_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_validProposalTransitions(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_validProposalTransitions,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().ValidProposalTransitions(ctx, fc.Args["state"].(ProposalState))
		},
		nil,
		ec.marshalNProposalState2ᚕmorningᚑgloryᚋinternalᚋgraphqlᚐProposalStateᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_validProposalTransitions(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type ProposalState does not have child fields")
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_validProposalTransitions_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_task(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_task,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Task(ctx, fc.Args["id"].(string))
		},
		nil,
		ec.marshalOTask2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐTask,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query_task(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Task_id(ctx, field)
			case "number":
				return ec.fieldContext_Task_number(ctx, field)
			case "proposalID":
				return ec.fieldContext_Task_proposalID(ctx, field)
			case "title":
				return ec.fieldContext_Task_title(ctx, field)
			case "description":
				return ec.fieldContext_Task_description(ctx, field)
			case "state":
				return ec.fieldContext_Task_state(ctx, field)
			case "priority":
				return ec.fieldContext_Task_priority(ctx, field)
			case "assigneeID":
				return ec.fieldContext_Task_assigneeID(ctx, field)
			case "startedAt":
				return ec.fieldContext_Task_startedAt(ctx, field)
			case "completedAt":
				return ec.fieldContext_Task_completedAt(ctx, field)
			case "createdAt":
				return ec.fieldContext_Task_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Task_updatedAt(ctx, field)
			case "proposal":
				return ec.fieldContext_Task_proposal(ctx, field)
			case "assignee":
				return ec.fieldContext_Task_assignee(ctx, field)
			case "issues":
				return ec.fieldContext_Task_issues(ctx, field)
			case "comments":
				return ec.fieldContext_Task_comments(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Task", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_task_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_tasks(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_tasks,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Tasks(ctx, fc.Args["proposalID"].(string), fc.Args["state"].(*TaskState), fc.Args["assigneeID"].(*string), fc.Args["search"].(*string), fc.Args["limit"].(*int32), fc.Args["offset"].(*int32))
		},
		nil,
		ec.marshalNTaskConnection2ᚖmorningᚑgloryᚋinternalᚋgraphqlᚐTaskConnection,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_tasks(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "edges":
				return ec.fieldContext_TaskConnection_edges(ctx, field)
			case "total":
				return ec.fieldContext_TaskConnection_total(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type TaskConnection", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_tasks_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_validTaskTransitions(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_validTaskTransitions,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().ValidTaskTransitions(ctx, fc.Args["state"].(TaskState))
		},
		nil,
		ec.marshalNTaskState2ᚕmorningᚑgloryᚋinternalᚋgraphqlᚐTaskStateᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_validTaskTransitions(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type TaskState does not have child fields")
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_validTaskTransitions_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_comments(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_comments,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Comments(ctx, fc.Args["issueID"].(*string), fc.Args["proposalID"].(*string), fc.Args["taskID"].(*string), fc.Args["orderBy"].(*string))
		},
		nil,
		ec.marshalNComment2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐCommentᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_comments(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Comment_id(ctx, field)
			case "number":
				return ec.fieldContext_Comment_number(ctx, field)
			case "issueID":
				return ec.fieldContext_Comment_issueID(ctx, field)
			case "proposalID":
				return ec.fieldContext_Comment_proposalID(ctx, field)
			case "taskID":
				return ec.fieldContext_Comment_taskID(ctx, field)
			case "authorID":
				return ec.fieldContext_Comment_authorID(ctx, field)
			case "parentID":
				return ec.fieldContext_Comment_parentID(ctx, field)
			case "body":
				return ec.fieldContext_Comment_body(ctx, field)
			case "contentType":
				return ec.fieldContext_Comment_contentType(ctx, field)
			case "createdAt":
				return ec.fieldContext_Comment_createdAt(ctx, field)
			case "updatedAt":
				return ec.fieldContext_Comment_updatedAt(ctx, field)
			case "author":
				return ec.fieldContext_Comment_author(ctx, field)
			case "parent":
				return ec.fieldContext_Comment_parent(ctx, field)
			case "replies":
				return ec.fieldContext_Comment_replies(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Comment", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_comments_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_timeline(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_timeline,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Timeline(ctx, fc.Args["issueID"].(*string), fc.Args["proposalID"].(*string), fc.Args["taskID"].(*string))
		},
		nil,
		ec.marshalNTimelineEvent2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐTimelineEventᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_timeline(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_TimelineEvent_id(ctx, field)
			case "number":
				return ec.fieldContext_TimelineEvent_number(ctx, field)
			case "issueID":
				return ec.fieldContext_TimelineEvent_issueID(ctx, field)
			case "proposalID":
				return ec.fieldContext_TimelineEvent_proposalID(ctx, field)
			case "taskID":
				return ec.fieldContext_TimelineEvent_taskID(ctx, field)
			case "actorID":
				return ec.fieldContext_TimelineEvent_actorID(ctx, field)
			case "eventType":
				return ec.fieldContext_TimelineEvent_eventType(ctx, field)
			case "payload":
				return ec.fieldContext_TimelineEvent_payload(ctx, field)
			case "createdAt":
				return ec.fieldContext_TimelineEvent_createdAt(ctx, field)
			case "actor":
				return ec.fieldContext_TimelineEvent_actor(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type TimelineEvent", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_timeline_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_validTransitions(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_validTransitions,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().ValidTransitions(ctx, fc.Args["state"].(IssueState))
		},
		nil,
		ec.marshalNIssueState2ᚕmorningᚑgloryᚋinternalᚋgraphqlᚐIssueStateᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_validTransitions(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			return nil, errors.New("field of type IssueState does not have child fields")
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_validTransitions_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_feedback(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_feedback,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Feedback(ctx, fc.Args["targetType"].(FeedbackTargetType), fc.Args["targetID"].(string))
		},
		nil,
		ec.marshalNFeedback2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐFeedbackᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_feedback(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Feedback_id(ctx, field)
			case "number":
				return ec.fieldContext_Feedback_number(ctx, field)
			case "targetType":
				return ec.fieldContext_Feedback_targetType(ctx, field)
			case "targetID":
				return ec.fieldContext_Feedback_targetID(ctx, field)
			case "authorID":
				return ec.fieldContext_Feedback_authorID(ctx, field)
			case "rating":
				return ec.fieldContext_Feedback_rating(ctx, field)
			case "body":
				return ec.fieldContext_Feedback_body(ctx, field)
			case "createdAt":
				return ec.fieldContext_Feedback_createdAt(ctx, field)
			case "author":
				return ec.fieldContext_Feedback_author(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Feedback", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_feedback_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_notificationSettings(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_notificationSettings,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().NotificationSettings(ctx, fc.Args["agentID"].(string))
		},
		nil,
		ec.marshalNNotificationSetting2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐNotificationSettingᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_notificationSettings(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_NotificationSetting_id(ctx, field)
			case "agentID":
				return ec.fieldContext_NotificationSetting_agentID(ctx, field)
			case "notificationType":
				return ec.fieldContext_NotificationSetting_notificationType(ctx, field)
			case "enabled":
				return ec.fieldContext_NotificationSetting_enabled(ctx, field)
			case "channel":
				return ec.fieldContext_NotificationSetting_channel(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type NotificationSetting", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_notificationSettings_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_notificationTypes(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_notificationTypes,
		func(ctx context.Context) (any, error) {
			return ec.Resolvers.Query().NotificationTypes(ctx)
		},
		nil,
		ec.marshalNNotificationTypeInfo2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐNotificationTypeInfoᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_notificationTypes(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "type":
				return ec.fieldContext_NotificationTypeInfo_type(ctx, field)
			case "description":
				return ec.fieldContext_NotificationTypeInfo_description(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type NotificationTypeInfo", field.Name)
		},
	}
	return fc, nil
}

func (ec *executionContext) _Query_notifications(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_notifications,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Notifications(ctx, fc.Args["agentID"].(string))
		},
		nil,
		ec.marshalNNotificationEvent2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐNotificationEventᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_notifications(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_NotificationEvent_id(ctx, field)
			case "number":
				return ec.fieldContext_NotificationEvent_number(ctx, field)
			case "agentID":
				return ec.fieldContext_NotificationEvent_agentID(ctx, field)
			case "notificationType":
				return ec.fieldContext_NotificationEvent_notificationType(ctx, field)
			case "issueID":
				return ec.fieldContext_NotificationEvent_issueID(ctx, field)
			case "proposalID":
				return ec.fieldContext_NotificationEvent_proposalID(ctx, field)
			case "taskID":
				return ec.fieldContext_NotificationEvent_taskID(ctx, field)
			case "projectID":
				return ec.fieldContext_NotificationEvent_projectID(ctx, field)
			case "message":
				return ec.fieldContext_NotificationEvent_message(ctx, field)
			case "read":
				return ec.fieldContext_NotificationEvent_read(ctx, field)
			case "createdAt":
				return ec.fieldContext_NotificationEvent_createdAt(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type NotificationEvent", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_notifications_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query_webhooks(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query_webhooks,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.Resolvers.Query().Webhooks(ctx, fc.Args["projectID"].(string))
		},
		nil,
		ec.marshalNWebhook2ᚕᚖmorningᚑgloryᚋinternalᚋgraphqlᚐWebhookᚄ,
		true,
		true,
	)
}

func (ec *executionContext) fieldContext_Query_webhooks(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: true,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "id":
				return ec.fieldContext_Webhook_id(ctx, field)
			case "projectID":
				return ec.fieldContext_Webhook_projectID(ctx, field)
			case "agentID":
				return ec.fieldContext_Webhook_agentID(ctx, field)
			case "agent":
				return ec.fieldContext_Webhook_agent(ctx, field)
			case "name":
				return ec.fieldContext_Webhook_name(ctx, field)
			case "secret":
				return ec.fieldContext_Webhook_secret(ctx, field)
			case "enabled":
				return ec.fieldContext_Webhook_enabled(ctx, field)
			case "createdAt":
				return ec.fieldContext_Webhook_createdAt(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type Webhook", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query_webhooks_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query___type(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query___type,
		func(ctx context.Context) (any, error) {
			fc := graphql.GetFieldContext(ctx)
			return ec.IntrospectType(fc.Args["name"].(string))
		},
		nil,
		ec.marshalO__Type2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐType,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query___type(ctx context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "kind":
				return ec.fieldContext___Type_kind(ctx, field)
			case "name":
				return ec.fieldContext___Type_name(ctx, field)
			case "description":
				return ec.fieldContext___Type_description(ctx, field)
			case "specifiedByURL":
				return ec.fieldContext___Type_specifiedByURL(ctx, field)
			case "fields":
				return ec.fieldContext___Type_fields(ctx, field)
			case "interfaces":
				return ec.fieldContext___Type_interfaces(ctx, field)
			case "possibleTypes":
				return ec.fieldContext___Type_possibleTypes(ctx, field)
			case "enumValues":
				return ec.fieldContext___Type_enumValues(ctx, field)
			case "inputFields":
				return ec.fieldContext___Type_inputFields(ctx, field)
			case "ofType":
				return ec.fieldContext___Type_ofType(ctx, field)
			case "isOneOf":
				return ec.fieldContext___Type_isOneOf(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type __Type", field.Name)
		},
	}
	defer func() {
		if r := recover(); r != nil {
			err = ec.Recover(ctx, r)
			ec.Error(ctx, err)
		}
	}()
	ctx = graphql.WithFieldContext(ctx, fc)
	if fc.Args, err = ec.field_Query___type_args(ctx, field.ArgumentMap(ec.Variables)); err != nil {
		ec.Error(ctx, err)
		return fc, err
	}
	return fc, nil
}

func (ec *executionContext) _Query___schema(ctx context.Context, field graphql.CollectedField) (ret graphql.Marshaler) {
	return graphql.ResolveField(
		ctx,
		ec.OperationContext,
		field,
		ec.fieldContext_Query___schema,
		func(ctx context.Context) (any, error) {
			return ec.IntrospectSchema()
		},
		nil,
		ec.marshalO__Schema2ᚖgithubᚗcomᚋ99designsᚋgqlgenᚋgraphqlᚋintrospectionᚐSchema,
		true,
		false,
	)
}

func (ec *executionContext) fieldContext_Query___schema(_ context.Context, field graphql.CollectedField) (fc *graphql.FieldContext, err error) {
	fc = &graphql.FieldContext{
		Object:     "Query",
		Field:      field,
		IsMethod:   true,
		IsResolver: false,
		Child: func(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
			switch field.Name {
			case "description":
				return ec.fieldContext___Schema_description(ctx, field)
			case "types":
				return ec.fieldContext___Schema_types(ctx, field)
			case "queryType":
				return ec.fieldContext___Schema_queryType(ctx, field)
			case "mutationType":
				return ec.fieldContext___Schema_mutationType(ctx, field)
			case "subscriptionType":
				return ec.fieldContext___Schema_subscriptionType(ctx, field)
			case "directives":
				return ec.fieldContext___Schema_directives(ctx, field)
			}
			return nil, fmt.Errorf("no field named %q was found under type __Schema", field.Name)
		},
	}
	return fc, nil
}

// endregion **************************** field.gotpl *****************************

// region    **************************** input.gotpl *****************************

// endregion **************************** input.gotpl *****************************

// region    ************************** interface.gotpl ***************************

// endregion ************************** interface.gotpl ***************************

// region    **************************** object.gotpl ****************************

var queryImplementors = []string{"Query"}

func (ec *executionContext) _Query(ctx context.Context, sel ast.SelectionSet) graphql.Marshaler {
	fields := graphql.CollectFields(ec.OperationContext, sel, queryImplementors)
	ctx = graphql.WithFieldContext(ctx, &graphql.FieldContext{
		Object: "Query",
	})

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		innerCtx := graphql.WithRootFieldContext(ctx, &graphql.RootFieldContext{
			Object: field.Name,
			Field:  field,
		})

		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("Query")
		case "supportedModels":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_supportedModels(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "commonDeviceInfo":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_commonDeviceInfo(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "allowHumanRegistration":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_allowHumanRegistration(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "agents":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_agents(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "agent":
			field := field

			innerFunc := func(ctx context.Context, _ *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_agent(ctx, field)
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "projects":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_projects(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "project":
			field := field

			innerFunc := func(ctx context.Context, _ *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_project(ctx, field)
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "labels":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_labels(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "milestones":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_milestones(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "issue":
			field := field

			innerFunc := func(ctx context.Context, _ *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_issue(ctx, field)
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "issues":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_issues(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "proposal":
			field := field

			innerFunc := func(ctx context.Context, _ *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_proposal(ctx, field)
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "proposals":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_proposals(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "validProposalTransitions":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_validProposalTransitions(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "task":
			field := field

			innerFunc := func(ctx context.Context, _ *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_task(ctx, field)
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "tasks":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_tasks(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "validTaskTransitions":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_validTaskTransitions(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "comments":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_comments(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "timeline":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_timeline(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "validTransitions":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_validTransitions(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "feedback":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_feedback(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "notificationSettings":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_notificationSettings(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "notificationTypes":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_notificationTypes(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "notifications":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_notifications(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "webhooks":
			field := field

			innerFunc := func(ctx context.Context, fs *graphql.FieldSet) (res graphql.Marshaler) {
				defer func() {
					if r := recover(); r != nil {
						ec.Error(ctx, ec.Recover(ctx, r))
					}
				}()
				res = ec._Query_webhooks(ctx, field)
				if res == graphql.Null {
					atomic.AddUint32(&fs.Invalids, 1)
				}
				return res
			}

			rrm := func(ctx context.Context) graphql.Marshaler {
				return ec.OperationContext.RootResolverMiddleware(ctx,
					func(ctx context.Context) graphql.Marshaler { return innerFunc(ctx, out) })
			}

			out.Concurrently(i, func(ctx context.Context) graphql.Marshaler { return rrm(innerCtx) })
		case "__type":
			out.Values[i] = ec.OperationContext.RootResolverMiddleware(innerCtx, func(ctx context.Context) (res graphql.Marshaler) {
				return ec._Query___type(ctx, field)
			})
		case "__schema":
			out.Values[i] = ec.OperationContext.RootResolverMiddleware(innerCtx, func(ctx context.Context) (res graphql.Marshaler) {
				return ec._Query___schema(ctx, field)
			})
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	atomic.AddInt32(&ec.Deferred, int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// endregion **************************** object.gotpl ****************************

// region    ***************************** type.gotpl *****************************

// endregion ***************************** type.gotpl *****************************
