// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"sync/atomic"
	"time"

	"github.com/99designs/gqlgen/graphql"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
	Subscription() SubscriptionResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Agent struct {
		AllowedCIDRs   func(childComplexity int) int
		AssignedIssues func(childComplexity int) int
		Capabilities   func(childComplexity int) int
		CreatedAt      func(childComplexity int) int
		CreatedIssues  func(childComplexity int) int
		DeviceInfo     func(childComplexity int) int
		Disabled       func(childComplexity int) int
		ExternalID     func(childComplexity int) int
		ID             func(childComplexity int) int
		Kind           func(childComplexity int) int
		LastIP         func(childComplexity int) int
		LastSeenAt     func(childComplexity int) int
		Metadata       func(childComplexity int) int
		ModelInfo      func(childComplexity int) int
		Name           func(childComplexity int) int
		Number         func(childComplexity int) int
		Status         func(childComplexity int) int
		SystemPrompt   func(childComplexity int) int
		TokenPreview   func(childComplexity int) int
		UpdatedAt      func(childComplexity int) int
	}

	AgentStatusEvent struct {
		AgentID   func(childComplexity int) int
		Status    func(childComplexity int) int
		Timestamp func(childComplexity int) int
	}

	Comment struct {
		Author      func(childComplexity int) int
		AuthorID    func(childComplexity int) int
		Body        func(childComplexity int) int
		ContentType func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		ID          func(childComplexity int) int
		IssueID     func(childComplexity int) int
		Number      func(childComplexity int) int
		Parent      func(childComplexity int) int
		ParentID    func(childComplexity int) int
		ProposalID  func(childComplexity int) int
		Replies     func(childComplexity int) int
		TaskID      func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	Feedback struct {
		Author     func(childComplexity int) int
		AuthorID   func(childComplexity int) int
		Body       func(childComplexity int) int
		CreatedAt  func(childComplexity int) int
		ID         func(childComplexity int) int
		Number     func(childComplexity int) int
		Rating     func(childComplexity int) int
		TargetID   func(childComplexity int) int
		TargetType func(childComplexity int) int
	}

	Issue struct {
		Assignees        func(childComplexity int) int
		Branch           func(childComplexity int) int
		Children         func(childComplexity int) int
		ClosedAt         func(childComplexity int) int
		CompletedAt      func(childComplexity int) int
		CreatedAt        func(childComplexity int) int
		Creator          func(childComplexity int) int
		CreatorID        func(childComplexity int) int
		Description      func(childComplexity int) int
		Difficulty       func(childComplexity int) int
		DueDate          func(childComplexity int) int
		Environment      func(childComplexity int) int
		ID               func(childComplexity int) int
		Labels           func(childComplexity int) int
		Links            func(childComplexity int) int
		Milestone        func(childComplexity int) int
		Number           func(childComplexity int) int
		ParentID         func(childComplexity int) int
		Priority         func(childComplexity int) int
		ProjectID        func(childComplexity int) int
		StartedAt        func(childComplexity int) int
		State            func(childComplexity int) int
		StructuredOutput func(childComplexity int) int
		Title            func(childComplexity int) int
		UpdatedAt        func(childComplexity int) int
	}

	IssueAssignee struct {
		Agent      func(childComplexity int) int
		AgentID    func(childComplexity int) int
		AssignedAt func(childComplexity int) int
		ID         func(childComplexity int) int
		IssueID    func(childComplexity int) int
		Number     func(childComplexity int) int
		State      func(childComplexity int) int
	}

	IssueConnection struct {
		Edges func(childComplexity int) int
		Total func(childComplexity int) int
	}

	Label struct {
		Capability  func(childComplexity int) int
		Color       func(childComplexity int) int
		Description func(childComplexity int) int
		Group       func(childComplexity int) int
		ID          func(childComplexity int) int
		Name        func(childComplexity int) int
		Number      func(childComplexity int) int
		ProjectID   func(childComplexity int) int
	}

	LoginResult struct {
		Agent func(childComplexity int) int
		Token func(childComplexity int) int
	}

	Milestone struct {
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		DueDate     func(childComplexity int) int
		ID          func(childComplexity int) int
		Number      func(childComplexity int) int
		ProjectID   func(childComplexity int) int
		State       func(childComplexity int) int
		Title       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	Mutation struct {
		AddAssignee               func(childComplexity int, issueID string, agentID string) int
		AddComment                func(childComplexity int, issueID string, authorID string, body string, contentType CommentContentType, parentID *string) int
		AddLabels                 func(childComplexity int, issueID string, labelIDs []string) int
		AddProjectMember          func(childComplexity int, projectID string, agentID string, role ProjectRole) int
		AddProposalComment        func(childComplexity int, proposalID string, authorID string, body string, contentType CommentContentType) int
		AddTaskComment            func(childComplexity int, taskID string, authorID string, body string, contentType CommentContentType) int
		AssignTask                func(childComplexity int, id string, assigneeID string) int
		CreateFeedback            func(childComplexity int, targetType FeedbackTargetType, targetID string, authorID string, rating FeedbackRating, body *string) int
		CreateIssue               func(childComplexity int, projectID string, title string, description *string, priority Priority, assigneeIDs []string, labelIDs []string, milestoneID *string, environment *string, branch *string, links []string) int
		CreateLabel               func(childComplexity int, projectID string, name string, color *string, capability *string, group *string) int
		CreateMilestone           func(childComplexity int, projectID string, title string, description *string, dueDate *time.Time) int
		CreateProject             func(childComplexity int, name string, description *string) int
		CreateProjectAgent        func(childComplexity int, projectID string, name string, kind AgentKind, role *ProjectRole, externalID *string, secret *string, capabilities []string, deviceInfo *string, modelInfo *string) int
		CreateProposal            func(childComplexity int, projectID string, title string, description *string, priority Priority, labelIDs []string) int
		CreateTask                func(childComplexity int, proposalID string, title string, description *string, priority *Priority, assigneeID *string) int
		DeleteAgent               func(childComplexity int, id string) int
		DeleteComment             func(childComplexity int, id string) int
		DeleteIssue               func(childComplexity int, id string) int
		DeleteLabel               func(childComplexity int, id string) int
		DeleteMilestone           func(childComplexity int, id string) int
		DeleteProject             func(childComplexity int, id string) int
		DeleteProposal            func(childComplexity int, id string) int
		DeleteTask                func(childComplexity int, id string) int
		LinkIssuesToTask          func(childComplexity int, taskID string, issueIDs []string) int
		LoginAgent                func(childComplexity int, externalID string, secret string) int
		MarkAllNotificationsRead  func(childComplexity int, agentID string) int
		MarkNotificationRead      func(childComplexity int, id string) int
		RegisterAgent             func(childComplexity int, name string, kind AgentKind, externalID string, secret string, capabilities []string, deviceInfo *string, modelInfo *string) int
		RemoveAssignee            func(childComplexity int, issueID string, agentID string) int
		RemoveLabels              func(childComplexity int, issueID string, labelIDs []string) int
		RemoveProjectMember       func(childComplexity int, projectID string, agentID string) int
		ReviewProposal            func(childComplexity int, id string, reviewerID string, approved bool, note *string) int
		TransitionIssue           func(childComplexity int, id string, newState IssueState, actorID string, note *string) int
		TransitionProposal        func(childComplexity int, id string, newState ProposalState, actorID string, note *string) int
		UnlinkIssueFromTask       func(childComplexity int, taskID string, issueID string) int
		UpdateAgent               func(childComplexity int, id string, systemPrompt *string) int
		UpdateAgentAllowedCIDRs   func(childComplexity int, id string, allowedCIDRs []string) int
		UpdateAgentDisabled       func(childComplexity int, id string, disabled bool) int
		UpdateAgentStatus         func(childComplexity int, id string, status AgentStatus) int
		UpdateAssigneeState       func(childComplexity int, issueID string, agentID string, state AssigneeState) int
		UpdateComment             func(childComplexity int, id string, body string) int
		UpdateIssue               func(childComplexity int, id string, title *string, description *string, priority *Priority, dueDate *time.Time, milestoneID *string, environment *string, branch *string, links []string, startedAt *time.Time, completedAt *time.Time, difficulty *int32) int
		UpdateLabel               func(childComplexity int, id string, name *string, color *string) int
		UpdateMilestone           func(childComplexity int, id string, title *string, description *string, dueDate *time.Time, state *MilestoneState) int
		UpdateNotificationSetting func(childComplexity int, agentID string, notificationType string, enabled bool, channel *string) int
		UpdateProject             func(childComplexity int, id string, name *string, description *string) int
		UpdateProjectConfig       func(childComplexity int, id string, allowCreatorTransition *bool, requireCreatorCloseApproval *bool) int
		UpdateProjectMember       func(childComplexity int, projectID string, agentID string, role ProjectRole) int
		UpdateProposal            func(childComplexity int, id string, title *string, description *string, priority *Priority) int
		UpdateTask                func(childComplexity int, id string, title *string, description *string, priority *Priority, state *TaskState) int
	}

	NotificationEvent struct {
		AgentID          func(childComplexity int) int
		CreatedAt        func(childComplexity int) int
		ID               func(childComplexity int) int
		IssueID          func(childComplexity int) int
		Message          func(childComplexity int) int
		NotificationType func(childComplexity int) int
		Number           func(childComplexity int) int
		ProjectID        func(childComplexity int) int
		ProposalID       func(childComplexity int) int
		Read             func(childComplexity int) int
		TaskID           func(childComplexity int) int
	}

	NotificationSetting struct {
		AgentID          func(childComplexity int) int
		Channel          func(childComplexity int) int
		Enabled          func(childComplexity int) int
		ID               func(childComplexity int) int
		NotificationType func(childComplexity int) int
	}

	NotificationTypeInfo struct {
		Description func(childComplexity int) int
		Type        func(childComplexity int) int
	}

	Project struct {
		AllowCreatorTransition      func(childComplexity int) int
		CreatedAt                   func(childComplexity int) int
		Description                 func(childComplexity int) int
		ID                          func(childComplexity int) int
		Labels                      func(childComplexity int) int
		Members                     func(childComplexity int) int
		Milestones                  func(childComplexity int) int
		Name                        func(childComplexity int) int
		Number                      func(childComplexity int) int
		RequireCreatorCloseApproval func(childComplexity int) int
		UpdatedAt                   func(childComplexity int) int
	}

	ProjectMember struct {
		Agent     func(childComplexity int) int
		AgentID   func(childComplexity int) int
		ID        func(childComplexity int) int
		Number    func(childComplexity int) int
		ProjectID func(childComplexity int) int
		Role      func(childComplexity int) int
	}

	Proposal struct {
		ApprovedAt  func(childComplexity int) int
		Author      func(childComplexity int) int
		AuthorID    func(childComplexity int) int
		CancelledAt func(childComplexity int) int
		Comments    func(childComplexity int) int
		CompletedAt func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		Labels      func(childComplexity int) int
		Number      func(childComplexity int) int
		Priority    func(childComplexity int) int
		ProjectID   func(childComplexity int) int
		ReviewNote  func(childComplexity int) int
		ReviewedAt  func(childComplexity int) int
		Reviewer    func(childComplexity int) int
		ReviewerID  func(childComplexity int) int
		StartedAt   func(childComplexity int) int
		State       func(childComplexity int) int
		SubmittedAt func(childComplexity int) int
		Tasks       func(childComplexity int) int
		Title       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	ProposalConnection struct {
		Edges func(childComplexity int) int
		Total func(childComplexity int) int
	}

	Query struct {
		Agent                    func(childComplexity int, id string) int
		Agents                   func(childComplexity int, kind *AgentKind, status *AgentStatus, capabilities []string, projectID *string) int
		AllowHumanRegistration   func(childComplexity int) int
		Comments                 func(childComplexity int, issueID *string, proposalID *string, taskID *string) int
		CommonDeviceInfo         func(childComplexity int) int
		Feedback                 func(childComplexity int, targetType FeedbackTargetType, targetID string) int
		Issue                    func(childComplexity int, id string) int
		Issues                   func(childComplexity int, projectID string, state *IssueState, states []IssueState, priority *Priority, assigneeID *string, labelIDs []string, search *string, limit *int32, offset *int32) int
		Labels                   func(childComplexity int, projectID string, group *string) int
		Milestones               func(childComplexity int, projectID string, state *MilestoneState) int
		NotificationSettings     func(childComplexity int, agentID string) int
		NotificationTypes        func(childComplexity int) int
		Notifications            func(childComplexity int, agentID string) int
		Project                  func(childComplexity int, id string) int
		Projects                 func(childComplexity int) int
		Proposal                 func(childComplexity int, id string) int
		Proposals                func(childComplexity int, projectID string, state *ProposalState, priority *Priority, search *string, limit *int32, offset *int32) int
		SupportedModels          func(childComplexity int) int
		Task                     func(childComplexity int, id string) int
		Tasks                    func(childComplexity int, proposalID string, state *TaskState, assigneeID *string, search *string, limit *int32, offset *int32) int
		Timeline                 func(childComplexity int, issueID *string, proposalID *string, taskID *string) int
		ValidProposalTransitions func(childComplexity int, state ProposalState) int
		ValidTaskTransitions     func(childComplexity int, state TaskState) int
		ValidTransitions         func(childComplexity int, state IssueState) int
	}

	RegisterResult struct {
		Agent func(childComplexity int) int
		Token func(childComplexity int) int
	}

	Subscription struct {
		AgentNotifications func(childComplexity int, agentID string) int
		AgentStatusChanged func(childComplexity int) int
		IssueUpdated       func(childComplexity int, issueID string) int
	}

	Task struct {
		Assignee    func(childComplexity int) int
		AssigneeID  func(childComplexity int) int
		Comments    func(childComplexity int) int
		CompletedAt func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		Issues      func(childComplexity int) int
		Number      func(childComplexity int) int
		Priority    func(childComplexity int) int
		Proposal    func(childComplexity int) int
		ProposalID  func(childComplexity int) int
		StartedAt   func(childComplexity int) int
		State       func(childComplexity int) int
		Title       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	TaskConnection struct {
		Edges func(childComplexity int) int
		Total func(childComplexity int) int
	}

	TimelineEvent struct {
		Actor      func(childComplexity int) int
		ActorID    func(childComplexity int) int
		CreatedAt  func(childComplexity int) int
		EventType  func(childComplexity int) int
		ID         func(childComplexity int) int
		IssueID    func(childComplexity int) int
		Number     func(childComplexity int) int
		Payload    func(childComplexity int) int
		ProposalID func(childComplexity int) int
		TaskID     func(childComplexity int) int
	}
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "Agent.allowedCIDRs":
		if e.ComplexityRoot.Agent.AllowedCIDRs == nil {
			break
		}

		return e.ComplexityRoot.Agent.AllowedCIDRs(childComplexity), true

	case "Agent.assignedIssues":
		if e.ComplexityRoot.Agent.AssignedIssues == nil {
			break
		}

		return e.ComplexityRoot.Agent.AssignedIssues(childComplexity), true

	case "Agent.capabilities":
		if e.ComplexityRoot.Agent.Capabilities == nil {
			break
		}

		return e.ComplexityRoot.Agent.Capabilities(childComplexity), true

	case "Agent.createdAt":
		if e.ComplexityRoot.Agent.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Agent.CreatedAt(childComplexity), true

	case "Agent.createdIssues":
		if e.ComplexityRoot.Agent.CreatedIssues == nil {
			break
		}

		return e.ComplexityRoot.Agent.CreatedIssues(childComplexity), true

	case "Agent.deviceInfo":
		if e.ComplexityRoot.Agent.DeviceInfo == nil {
			break
		}

		return e.ComplexityRoot.Agent.DeviceInfo(childComplexity), true

	case "Agent.disabled":
		if e.ComplexityRoot.Agent.Disabled == nil {
			break
		}

		return e.ComplexityRoot.Agent.Disabled(childComplexity), true

	case "Agent.externalID":
		if e.ComplexityRoot.Agent.ExternalID == nil {
			break
		}

		return e.ComplexityRoot.Agent.ExternalID(childComplexity), true

	case "Agent.id":
		if e.ComplexityRoot.Agent.ID == nil {
			break
		}

		return e.ComplexityRoot.Agent.ID(childComplexity), true

	case "Agent.kind":
		if e.ComplexityRoot.Agent.Kind == nil {
			break
		}

		return e.ComplexityRoot.Agent.Kind(childComplexity), true

	case "Agent.lastIP":
		if e.ComplexityRoot.Agent.LastIP == nil {
			break
		}

		return e.ComplexityRoot.Agent.LastIP(childComplexity), true

	case "Agent.lastSeenAt":
		if e.ComplexityRoot.Agent.LastSeenAt == nil {
			break
		}

		return e.ComplexityRoot.Agent.LastSeenAt(childComplexity), true

	case "Agent.metadata":
		if e.ComplexityRoot.Agent.Metadata == nil {
			break
		}

		return e.ComplexityRoot.Agent.Metadata(childComplexity), true

	case "Agent.modelInfo":
		if e.ComplexityRoot.Agent.ModelInfo == nil {
			break
		}

		return e.ComplexityRoot.Agent.ModelInfo(childComplexity), true

	case "Agent.name":
		if e.ComplexityRoot.Agent.Name == nil {
			break
		}

		return e.ComplexityRoot.Agent.Name(childComplexity), true

	case "Agent.number":
		if e.ComplexityRoot.Agent.Number == nil {
			break
		}

		return e.ComplexityRoot.Agent.Number(childComplexity), true

	case "Agent.status":
		if e.ComplexityRoot.Agent.Status == nil {
			break
		}

		return e.ComplexityRoot.Agent.Status(childComplexity), true

	case "Agent.systemPrompt":
		if e.ComplexityRoot.Agent.SystemPrompt == nil {
			break
		}

		return e.ComplexityRoot.Agent.SystemPrompt(childComplexity), true

	case "Agent.tokenPreview":
		if e.ComplexityRoot.Agent.TokenPreview == nil {
			break
		}

		return e.ComplexityRoot.Agent.TokenPreview(childComplexity), true

	case "Agent.updatedAt":
		if e.ComplexityRoot.Agent.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Agent.UpdatedAt(childComplexity), true

	case "AgentStatusEvent.agentID":
		if e.ComplexityRoot.AgentStatusEvent.AgentID == nil {
			break
		}

		return e.ComplexityRoot.AgentStatusEvent.AgentID(childComplexity), true

	case "AgentStatusEvent.status":
		if e.ComplexityRoot.AgentStatusEvent.Status == nil {
			break
		}

		return e.ComplexityRoot.AgentStatusEvent.Status(childComplexity), true

	case "AgentStatusEvent.timestamp":
		if e.ComplexityRoot.AgentStatusEvent.Timestamp == nil {
			break
		}

		return e.ComplexityRoot.AgentStatusEvent.Timestamp(childComplexity), true

	case "Comment.author":
		if e.ComplexityRoot.Comment.Author == nil {
			break
		}

		return e.ComplexityRoot.Comment.Author(childComplexity), true

	case "Comment.authorID":
		if e.ComplexityRoot.Comment.AuthorID == nil {
			break
		}

		return e.ComplexityRoot.Comment.AuthorID(childComplexity), true

	case "Comment.body":
		if e.ComplexityRoot.Comment.Body == nil {
			break
		}

		return e.ComplexityRoot.Comment.Body(childComplexity), true

	case "Comment.contentType":
		if e.ComplexityRoot.Comment.ContentType == nil {
			break
		}

		return e.ComplexityRoot.Comment.ContentType(childComplexity), true

	case "Comment.createdAt":
		if e.ComplexityRoot.Comment.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Comment.CreatedAt(childComplexity), true

	case "Comment.id":
		if e.ComplexityRoot.Comment.ID == nil {
			break
		}

		return e.ComplexityRoot.Comment.ID(childComplexity), true

	case "Comment.issueID":
		if e.ComplexityRoot.Comment.IssueID == nil {
			break
		}

		return e.ComplexityRoot.Comment.IssueID(childComplexity), true

	case "Comment.number":
		if e.ComplexityRoot.Comment.Number == nil {
			break
		}

		return e.ComplexityRoot.Comment.Number(childComplexity), true

	case "Comment.parent":
		if e.ComplexityRoot.Comment.Parent == nil {
			break
		}

		return e.ComplexityRoot.Comment.Parent(childComplexity), true

	case "Comment.parentID":
		if e.ComplexityRoot.Comment.ParentID == nil {
			break
		}

		return e.ComplexityRoot.Comment.ParentID(childComplexity), true

	case "Comment.proposalID":
		if e.ComplexityRoot.Comment.ProposalID == nil {
			break
		}

		return e.ComplexityRoot.Comment.ProposalID(childComplexity), true

	case "Comment.replies":
		if e.ComplexityRoot.Comment.Replies == nil {
			break
		}

		return e.ComplexityRoot.Comment.Replies(childComplexity), true

	case "Comment.taskID":
		if e.ComplexityRoot.Comment.TaskID == nil {
			break
		}

		return e.ComplexityRoot.Comment.TaskID(childComplexity), true

	case "Comment.updatedAt":
		if e.ComplexityRoot.Comment.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Comment.UpdatedAt(childComplexity), true

	case "Feedback.author":
		if e.ComplexityRoot.Feedback.Author == nil {
			break
		}

		return e.ComplexityRoot.Feedback.Author(childComplexity), true

	case "Feedback.authorID":
		if e.ComplexityRoot.Feedback.AuthorID == nil {
			break
		}

		return e.ComplexityRoot.Feedback.AuthorID(childComplexity), true

	case "Feedback.body":
		if e.ComplexityRoot.Feedback.Body == nil {
			break
		}

		return e.ComplexityRoot.Feedback.Body(childComplexity), true

	case "Feedback.createdAt":
		if e.ComplexityRoot.Feedback.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Feedback.CreatedAt(childComplexity), true

	case "Feedback.id":
		if e.ComplexityRoot.Feedback.ID == nil {
			break
		}

		return e.ComplexityRoot.Feedback.ID(childComplexity), true

	case "Feedback.number":
		if e.ComplexityRoot.Feedback.Number == nil {
			break
		}

		return e.ComplexityRoot.Feedback.Number(childComplexity), true

	case "Feedback.rating":
		if e.ComplexityRoot.Feedback.Rating == nil {
			break
		}

		return e.ComplexityRoot.Feedback.Rating(childComplexity), true

	case "Feedback.targetID":
		if e.ComplexityRoot.Feedback.TargetID == nil {
			break
		}

		return e.ComplexityRoot.Feedback.TargetID(childComplexity), true

	case "Feedback.targetType":
		if e.ComplexityRoot.Feedback.TargetType == nil {
			break
		}

		return e.ComplexityRoot.Feedback.TargetType(childComplexity), true

	case "Issue.assignees":
		if e.ComplexityRoot.Issue.Assignees == nil {
			break
		}

		return e.ComplexityRoot.Issue.Assignees(childComplexity), true

	case "Issue.branch":
		if e.ComplexityRoot.Issue.Branch == nil {
			break
		}

		return e.ComplexityRoot.Issue.Branch(childComplexity), true

	case "Issue.children":
		if e.ComplexityRoot.Issue.Children == nil {
			break
		}

		return e.ComplexityRoot.Issue.Children(childComplexity), true

	case "Issue.closedAt":
		if e.ComplexityRoot.Issue.ClosedAt == nil {
			break
		}

		return e.ComplexityRoot.Issue.ClosedAt(childComplexity), true

	case "Issue.completedAt":
		if e.ComplexityRoot.Issue.CompletedAt == nil {
			break
		}

		return e.ComplexityRoot.Issue.CompletedAt(childComplexity), true

	case "Issue.createdAt":
		if e.ComplexityRoot.Issue.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Issue.CreatedAt(childComplexity), true

	case "Issue.creator":
		if e.ComplexityRoot.Issue.Creator == nil {
			break
		}

		return e.ComplexityRoot.Issue.Creator(childComplexity), true

	case "Issue.creatorID":
		if e.ComplexityRoot.Issue.CreatorID == nil {
			break
		}

		return e.ComplexityRoot.Issue.CreatorID(childComplexity), true

	case "Issue.description":
		if e.ComplexityRoot.Issue.Description == nil {
			break
		}

		return e.ComplexityRoot.Issue.Description(childComplexity), true

	case "Issue.difficulty":
		if e.ComplexityRoot.Issue.Difficulty == nil {
			break
		}

		return e.ComplexityRoot.Issue.Difficulty(childComplexity), true

	case "Issue.dueDate":
		if e.ComplexityRoot.Issue.DueDate == nil {
			break
		}

		return e.ComplexityRoot.Issue.DueDate(childComplexity), true

	case "Issue.environment":
		if e.ComplexityRoot.Issue.Environment == nil {
			break
		}

		return e.ComplexityRoot.Issue.Environment(childComplexity), true

	case "Issue.id":
		if e.ComplexityRoot.Issue.ID == nil {
			break
		}

		return e.ComplexityRoot.Issue.ID(childComplexity), true

	case "Issue.labels":
		if e.ComplexityRoot.Issue.Labels == nil {
			break
		}

		return e.ComplexityRoot.Issue.Labels(childComplexity), true

	case "Issue.links":
		if e.ComplexityRoot.Issue.Links == nil {
			break
		}

		return e.ComplexityRoot.Issue.Links(childComplexity), true

	case "Issue.milestone":
		if e.ComplexityRoot.Issue.Milestone == nil {
			break
		}

		return e.ComplexityRoot.Issue.Milestone(childComplexity), true

	case "Issue.number":
		if e.ComplexityRoot.Issue.Number == nil {
			break
		}

		return e.ComplexityRoot.Issue.Number(childComplexity), true

	case "Issue.parentID":
		if e.ComplexityRoot.Issue.ParentID == nil {
			break
		}

		return e.ComplexityRoot.Issue.ParentID(childComplexity), true

	case "Issue.priority":
		if e.ComplexityRoot.Issue.Priority == nil {
			break
		}

		return e.ComplexityRoot.Issue.Priority(childComplexity), true

	case "Issue.projectID":
		if e.ComplexityRoot.Issue.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.Issue.ProjectID(childComplexity), true

	case "Issue.startedAt":
		if e.ComplexityRoot.Issue.StartedAt == nil {
			break
		}

		return e.ComplexityRoot.Issue.StartedAt(childComplexity), true

	case "Issue.state":
		if e.ComplexityRoot.Issue.State == nil {
			break
		}

		return e.ComplexityRoot.Issue.State(childComplexity), true

	case "Issue.structuredOutput":
		if e.ComplexityRoot.Issue.StructuredOutput == nil {
			break
		}

		return e.ComplexityRoot.Issue.StructuredOutput(childComplexity), true

	case "Issue.title":
		if e.ComplexityRoot.Issue.Title == nil {
			break
		}

		return e.ComplexityRoot.Issue.Title(childComplexity), true

	case "Issue.updatedAt":
		if e.ComplexityRoot.Issue.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Issue.UpdatedAt(childComplexity), true

	case "IssueAssignee.agent":
		if e.ComplexityRoot.IssueAssignee.Agent == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.Agent(childComplexity), true

	case "IssueAssignee.agentID":
		if e.ComplexityRoot.IssueAssignee.AgentID == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.AgentID(childComplexity), true

	case "IssueAssignee.assignedAt":
		if e.ComplexityRoot.IssueAssignee.AssignedAt == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.AssignedAt(childComplexity), true

	case "IssueAssignee.id":
		if e.ComplexityRoot.IssueAssignee.ID == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.ID(childComplexity), true

	case "IssueAssignee.issueID":
		if e.ComplexityRoot.IssueAssignee.IssueID == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.IssueID(childComplexity), true

	case "IssueAssignee.number":
		if e.ComplexityRoot.IssueAssignee.Number == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.Number(childComplexity), true

	case "IssueAssignee.state":
		if e.ComplexityRoot.IssueAssignee.State == nil {
			break
		}

		return e.ComplexityRoot.IssueAssignee.State(childComplexity), true

	case "IssueConnection.edges":
		if e.ComplexityRoot.IssueConnection.Edges == nil {
			break
		}

		return e.ComplexityRoot.IssueConnection.Edges(childComplexity), true

	case "IssueConnection.total":
		if e.ComplexityRoot.IssueConnection.Total == nil {
			break
		}

		return e.ComplexityRoot.IssueConnection.Total(childComplexity), true

	case "Label.capability":
		if e.ComplexityRoot.Label.Capability == nil {
			break
		}

		return e.ComplexityRoot.Label.Capability(childComplexity), true

	case "Label.color":
		if e.ComplexityRoot.Label.Color == nil {
			break
		}

		return e.ComplexityRoot.Label.Color(childComplexity), true

	case "Label.description":
		if e.ComplexityRoot.Label.Description == nil {
			break
		}

		return e.ComplexityRoot.Label.Description(childComplexity), true

	case "Label.group":
		if e.ComplexityRoot.Label.Group == nil {
			break
		}

		return e.ComplexityRoot.Label.Group(childComplexity), true

	case "Label.id":
		if e.ComplexityRoot.Label.ID == nil {
			break
		}

		return e.ComplexityRoot.Label.ID(childComplexity), true

	case "Label.name":
		if e.ComplexityRoot.Label.Name == nil {
			break
		}

		return e.ComplexityRoot.Label.Name(childComplexity), true

	case "Label.number":
		if e.ComplexityRoot.Label.Number == nil {
			break
		}

		return e.ComplexityRoot.Label.Number(childComplexity), true

	case "Label.projectID":
		if e.ComplexityRoot.Label.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.Label.ProjectID(childComplexity), true

	case "LoginResult.agent":
		if e.ComplexityRoot.LoginResult.Agent == nil {
			break
		}

		return e.ComplexityRoot.LoginResult.Agent(childComplexity), true

	case "LoginResult.token":
		if e.ComplexityRoot.LoginResult.Token == nil {
			break
		}

		return e.ComplexityRoot.LoginResult.Token(childComplexity), true

	case "Milestone.createdAt":
		if e.ComplexityRoot.Milestone.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Milestone.CreatedAt(childComplexity), true

	case "Milestone.description":
		if e.ComplexityRoot.Milestone.Description == nil {
			break
		}

		return e.ComplexityRoot.Milestone.Description(childComplexity), true

	case "Milestone.dueDate":
		if e.ComplexityRoot.Milestone.DueDate == nil {
			break
		}

		return e.ComplexityRoot.Milestone.DueDate(childComplexity), true

	case "Milestone.id":
		if e.ComplexityRoot.Milestone.ID == nil {
			break
		}

		return e.ComplexityRoot.Milestone.ID(childComplexity), true

	case "Milestone.number":
		if e.ComplexityRoot.Milestone.Number == nil {
			break
		}

		return e.ComplexityRoot.Milestone.Number(childComplexity), true

	case "Milestone.projectID":
		if e.ComplexityRoot.Milestone.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.Milestone.ProjectID(childComplexity), true

	case "Milestone.state":
		if e.ComplexityRoot.Milestone.State == nil {
			break
		}

		return e.ComplexityRoot.Milestone.State(childComplexity), true

	case "Milestone.title":
		if e.ComplexityRoot.Milestone.Title == nil {
			break
		}

		return e.ComplexityRoot.Milestone.Title(childComplexity), true

	case "Milestone.updatedAt":
		if e.ComplexityRoot.Milestone.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Milestone.UpdatedAt(childComplexity), true

	case "Mutation.addAssignee":
		if e.ComplexityRoot.Mutation.AddAssignee == nil {
			break
		}

		args, err := ec.field_Mutation_addAssignee_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddAssignee(childComplexity, args["issueID"].(string), args["agentID"].(string)), true

	case "Mutation.addComment":
		if e.ComplexityRoot.Mutation.AddComment == nil {
			break
		}

		args, err := ec.field_Mutation_addComment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddComment(childComplexity, args["issueID"].(string), args["authorID"].(string), args["body"].(string), args["contentType"].(CommentContentType), args["parentID"].(*string)), true

	case "Mutation.addLabels":
		if e.ComplexityRoot.Mutation.AddLabels == nil {
			break
		}

		args, err := ec.field_Mutation_addLabels_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddLabels(childComplexity, args["issueID"].(string), args["labelIDs"].([]string)), true

	case "Mutation.addProjectMember":
		if e.ComplexityRoot.Mutation.AddProjectMember == nil {
			break
		}

		args, err := ec.field_Mutation_addProjectMember_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddProjectMember(childComplexity, args["projectID"].(string), args["agentID"].(string), args["role"].(ProjectRole)), true

	case "Mutation.addProposalComment":
		if e.ComplexityRoot.Mutation.AddProposalComment == nil {
			break
		}

		args, err := ec.field_Mutation_addProposalComment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddProposalComment(childComplexity, args["proposalID"].(string), args["authorID"].(string), args["body"].(string), args["contentType"].(CommentContentType)), true

	case "Mutation.addTaskComment":
		if e.ComplexityRoot.Mutation.AddTaskComment == nil {
			break
		}

		args, err := ec.field_Mutation_addTaskComment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AddTaskComment(childComplexity, args["taskID"].(string), args["authorID"].(string), args["body"].(string), args["contentType"].(CommentContentType)), true

	case "Mutation.assignTask":
		if e.ComplexityRoot.Mutation.AssignTask == nil {
			break
		}

		args, err := ec.field_Mutation_assignTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.AssignTask(childComplexity, args["id"].(string), args["assigneeID"].(string)), true

	case "Mutation.createFeedback":
		if e.ComplexityRoot.Mutation.CreateFeedback == nil {
			break
		}

		args, err := ec.field_Mutation_createFeedback_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateFeedback(childComplexity, args["targetType"].(FeedbackTargetType), args["targetID"].(string), args["authorID"].(string), args["rating"].(FeedbackRating), args["body"].(*string)), true

	case "Mutation.createIssue":
		if e.ComplexityRoot.Mutation.CreateIssue == nil {
			break
		}

		args, err := ec.field_Mutation_createIssue_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateIssue(childComplexity, args["projectID"].(string), args["title"].(string), args["description"].(*string), args["priority"].(Priority), args["assigneeIDs"].([]string), args["labelIDs"].([]string), args["milestoneId"].(*string), args["environment"].(*string), args["branch"].(*string), args["links"].([]string)), true

	case "Mutation.createLabel":
		if e.ComplexityRoot.Mutation.CreateLabel == nil {
			break
		}

		args, err := ec.field_Mutation_createLabel_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateLabel(childComplexity, args["projectID"].(string), args["name"].(string), args["color"].(*string), args["capability"].(*string), args["group"].(*string)), true

	case "Mutation.createMilestone":
		if e.ComplexityRoot.Mutation.CreateMilestone == nil {
			break
		}

		args, err := ec.field_Mutation_createMilestone_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateMilestone(childComplexity, args["projectID"].(string), args["title"].(string), args["description"].(*string), args["dueDate"].(*time.Time)), true

	case "Mutation.createProject":
		if e.ComplexityRoot.Mutation.CreateProject == nil {
			break
		}

		args, err := ec.field_Mutation_createProject_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateProject(childComplexity, args["name"].(string), args["description"].(*string)), true

	case "Mutation.createProjectAgent":
		if e.ComplexityRoot.Mutation.CreateProjectAgent == nil {
			break
		}

		args, err := ec.field_Mutation_createProjectAgent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateProjectAgent(childComplexity, args["projectID"].(string), args["name"].(string), args["kind"].(AgentKind), args["role"].(*ProjectRole), args["externalID"].(*string), args["secret"].(*string), args["capabilities"].([]string), args["deviceInfo"].(*string), args["modelInfo"].(*string)), true

	case "Mutation.createProposal":
		if e.ComplexityRoot.Mutation.CreateProposal == nil {
			break
		}

		args, err := ec.field_Mutation_createProposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateProposal(childComplexity, args["projectID"].(string), args["title"].(string), args["description"].(*string), args["priority"].(Priority), args["labelIDs"].([]string)), true

	case "Mutation.createTask":
		if e.ComplexityRoot.Mutation.CreateTask == nil {
			break
		}

		args, err := ec.field_Mutation_createTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateTask(childComplexity, args["proposalID"].(string), args["title"].(string), args["description"].(*string), args["priority"].(*Priority), args["assigneeID"].(*string)), true

	case "Mutation.deleteAgent":
		if e.ComplexityRoot.Mutation.DeleteAgent == nil {
			break
		}

		args, err := ec.field_Mutation_deleteAgent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteAgent(childComplexity, args["id"].(string)), true

	case "Mutation.deleteComment":
		if e.ComplexityRoot.Mutation.DeleteComment == nil {
			break
		}

		args, err := ec.field_Mutation_deleteComment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteComment(childComplexity, args["id"].(string)), true

	case "Mutation.deleteIssue":
		if e.ComplexityRoot.Mutation.DeleteIssue == nil {
			break
		}

		args, err := ec.field_Mutation_deleteIssue_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteIssue(childComplexity, args["id"].(string)), true

	case "Mutation.deleteLabel":
		if e.ComplexityRoot.Mutation.DeleteLabel == nil {
			break
		}

		args, err := ec.field_Mutation_deleteLabel_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteLabel(childComplexity, args["id"].(string)), true

	case "Mutation.deleteMilestone":
		if e.ComplexityRoot.Mutation.DeleteMilestone == nil {
			break
		}

		args, err := ec.field_Mutation_deleteMilestone_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteMilestone(childComplexity, args["id"].(string)), true

	case "Mutation.deleteProject":
		if e.ComplexityRoot.Mutation.DeleteProject == nil {
			break
		}

		args, err := ec.field_Mutation_deleteProject_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteProject(childComplexity, args["id"].(string)), true

	case "Mutation.deleteProposal":
		if e.ComplexityRoot.Mutation.DeleteProposal == nil {
			break
		}

		args, err := ec.field_Mutation_deleteProposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteProposal(childComplexity, args["id"].(string)), true

	case "Mutation.deleteTask":
		if e.ComplexityRoot.Mutation.DeleteTask == nil {
			break
		}

		args, err := ec.field_Mutation_deleteTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteTask(childComplexity, args["id"].(string)), true

	case "Mutation.linkIssuesToTask":
		if e.ComplexityRoot.Mutation.LinkIssuesToTask == nil {
			break
		}

		args, err := ec.field_Mutation_linkIssuesToTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.LinkIssuesToTask(childComplexity, args["taskID"].(string), args["issueIDs"].([]string)), true

	case "Mutation.loginAgent":
		if e.ComplexityRoot.Mutation.LoginAgent == nil {
			break
		}

		args, err := ec.field_Mutation_loginAgent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.LoginAgent(childComplexity, args["externalID"].(string), args["secret"].(string)), true

	case "Mutation.markAllNotificationsRead":
		if e.ComplexityRoot.Mutation.MarkAllNotificationsRead == nil {
			break
		}

		args, err := ec.field_Mutation_markAllNotificationsRead_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.MarkAllNotificationsRead(childComplexity, args["agentID"].(string)), true

	case "Mutation.markNotificationRead":
		if e.ComplexityRoot.Mutation.MarkNotificationRead == nil {
			break
		}

		args, err := ec.field_Mutation_markNotificationRead_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.MarkNotificationRead(childComplexity, args["id"].(string)), true

	case "Mutation.registerAgent":
		if e.ComplexityRoot.Mutation.RegisterAgent == nil {
			break
		}

		args, err := ec.field_Mutation_registerAgent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.RegisterAgent(childComplexity, args["name"].(string), args["kind"].(AgentKind), args["externalID"].(string), args["secret"].(string), args["capabilities"].([]string), args["deviceInfo"].(*string), args["modelInfo"].(*string)), true

	case "Mutation.removeAssignee":
		if e.ComplexityRoot.Mutation.RemoveAssignee == nil {
			break
		}

		args, err := ec.field_Mutation_removeAssignee_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.RemoveAssignee(childComplexity, args["issueID"].(string), args["agentID"].(string)), true

	case "Mutation.removeLabels":
		if e.ComplexityRoot.Mutation.RemoveLabels == nil {
			break
		}

		args, err := ec.field_Mutation_removeLabels_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.RemoveLabels(childComplexity, args["issueID"].(string), args["labelIDs"].([]string)), true

	case "Mutation.removeProjectMember":
		if e.ComplexityRoot.Mutation.RemoveProjectMember == nil {
			break
		}

		args, err := ec.field_Mutation_removeProjectMember_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.RemoveProjectMember(childComplexity, args["projectID"].(string), args["agentID"].(string)), true

	case "Mutation.reviewProposal":
		if e.ComplexityRoot.Mutation.ReviewProposal == nil {
			break
		}

		args, err := ec.field_Mutation_reviewProposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.ReviewProposal(childComplexity, args["id"].(string), args["reviewerID"].(string), args["approved"].(bool), args["note"].(*string)), true

	case "Mutation.transitionIssue":
		if e.ComplexityRoot.Mutation.TransitionIssue == nil {
			break
		}

		args, err := ec.field_Mutation_transitionIssue_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.TransitionIssue(childComplexity, args["id"].(string), args["newState"].(IssueState), args["actorID"].(string), args["note"].(*string)), true

	case "Mutation.transitionProposal":
		if e.ComplexityRoot.Mutation.TransitionProposal == nil {
			break
		}

		args, err := ec.field_Mutation_transitionProposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.TransitionProposal(childComplexity, args["id"].(string), args["newState"].(ProposalState), args["actorID"].(string), args["note"].(*string)), true

	case "Mutation.unlinkIssueFromTask":
		if e.ComplexityRoot.Mutation.UnlinkIssueFromTask == nil {
			break
		}

		args, err := ec.field_Mutation_unlinkIssueFromTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UnlinkIssueFromTask(childComplexity, args["taskID"].(string), args["issueID"].(string)), true

	case "Mutation.updateAgent":
		if e.ComplexityRoot.Mutation.UpdateAgent == nil {
			break
		}

		args, err := ec.field_Mutation_updateAgent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateAgent(childComplexity, args["id"].(string), args["systemPrompt"].(*string)), true

	case "Mutation.updateAgentAllowedCIDRs":
		if e.ComplexityRoot.Mutation.UpdateAgentAllowedCIDRs == nil {
			break
		}

		args, err := ec.field_Mutation_updateAgentAllowedCIDRs_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateAgentAllowedCIDRs(childComplexity, args["id"].(string), args["allowedCIDRs"].([]string)), true

	case "Mutation.updateAgentDisabled":
		if e.ComplexityRoot.Mutation.UpdateAgentDisabled == nil {
			break
		}

		args, err := ec.field_Mutation_updateAgentDisabled_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateAgentDisabled(childComplexity, args["id"].(string), args["disabled"].(bool)), true

	case "Mutation.updateAgentStatus":
		if e.ComplexityRoot.Mutation.UpdateAgentStatus == nil {
			break
		}

		args, err := ec.field_Mutation_updateAgentStatus_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateAgentStatus(childComplexity, args["id"].(string), args["status"].(AgentStatus)), true

	case "Mutation.updateAssigneeState":
		if e.ComplexityRoot.Mutation.UpdateAssigneeState == nil {
			break
		}

		args, err := ec.field_Mutation_updateAssigneeState_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateAssigneeState(childComplexity, args["issueID"].(string), args["agentID"].(string), args["state"].(AssigneeState)), true

	case "Mutation.updateComment":
		if e.ComplexityRoot.Mutation.UpdateComment == nil {
			break
		}

		args, err := ec.field_Mutation_updateComment_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateComment(childComplexity, args["id"].(string), args["body"].(string)), true

	case "Mutation.updateIssue":
		if e.ComplexityRoot.Mutation.UpdateIssue == nil {
			break
		}

		args, err := ec.field_Mutation_updateIssue_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateIssue(childComplexity, args["id"].(string), args["title"].(*string), args["description"].(*string), args["priority"].(*Priority), args["dueDate"].(*time.Time), args["milestoneId"].(*string), args["environment"].(*string), args["branch"].(*string), args["links"].([]string), args["startedAt"].(*time.Time), args["completedAt"].(*time.Time), args["difficulty"].(*int32)), true

	case "Mutation.updateLabel":
		if e.ComplexityRoot.Mutation.UpdateLabel == nil {
			break
		}

		args, err := ec.field_Mutation_updateLabel_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateLabel(childComplexity, args["id"].(string), args["name"].(*string), args["color"].(*string)), true

	case "Mutation.updateMilestone":
		if e.ComplexityRoot.Mutation.UpdateMilestone == nil {
			break
		}

		args, err := ec.field_Mutation_updateMilestone_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateMilestone(childComplexity, args["id"].(string), args["title"].(*string), args["description"].(*string), args["dueDate"].(*time.Time), args["state"].(*MilestoneState)), true

	case "Mutation.updateNotificationSetting":
		if e.ComplexityRoot.Mutation.UpdateNotificationSetting == nil {
			break
		}

		args, err := ec.field_Mutation_updateNotificationSetting_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateNotificationSetting(childComplexity, args["agentID"].(string), args["notificationType"].(string), args["enabled"].(bool), args["channel"].(*string)), true

	case "Mutation.updateProject":
		if e.ComplexityRoot.Mutation.UpdateProject == nil {
			break
		}

		args, err := ec.field_Mutation_updateProject_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateProject(childComplexity, args["id"].(string), args["name"].(*string), args["description"].(*string)), true

	case "Mutation.updateProjectConfig":
		if e.ComplexityRoot.Mutation.UpdateProjectConfig == nil {
			break
		}

		args, err := ec.field_Mutation_updateProjectConfig_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateProjectConfig(childComplexity, args["id"].(string), args["allowCreatorTransition"].(*bool), args["requireCreatorCloseApproval"].(*bool)), true

	case "Mutation.updateProjectMember":
		if e.ComplexityRoot.Mutation.UpdateProjectMember == nil {
			break
		}

		args, err := ec.field_Mutation_updateProjectMember_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateProjectMember(childComplexity, args["projectID"].(string), args["agentID"].(string), args["role"].(ProjectRole)), true

	case "Mutation.updateProposal":
		if e.ComplexityRoot.Mutation.UpdateProposal == nil {
			break
		}

		args, err := ec.field_Mutation_updateProposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateProposal(childComplexity, args["id"].(string), args["title"].(*string), args["description"].(*string), args["priority"].(*Priority)), true

	case "Mutation.updateTask":
		if e.ComplexityRoot.Mutation.UpdateTask == nil {
			break
		}

		args, err := ec.field_Mutation_updateTask_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateTask(childComplexity, args["id"].(string), args["title"].(*string), args["description"].(*string), args["priority"].(*Priority), args["state"].(*TaskState)), true

	case "NotificationEvent.agentID":
		if e.ComplexityRoot.NotificationEvent.AgentID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.AgentID(childComplexity), true

	case "NotificationEvent.createdAt":
		if e.ComplexityRoot.NotificationEvent.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.CreatedAt(childComplexity), true

	case "NotificationEvent.id":
		if e.ComplexityRoot.NotificationEvent.ID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.ID(childComplexity), true

	case "NotificationEvent.issueID":
		if e.ComplexityRoot.NotificationEvent.IssueID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.IssueID(childComplexity), true

	case "NotificationEvent.message":
		if e.ComplexityRoot.NotificationEvent.Message == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.Message(childComplexity), true

	case "NotificationEvent.notificationType":
		if e.ComplexityRoot.NotificationEvent.NotificationType == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.NotificationType(childComplexity), true

	case "NotificationEvent.number":
		if e.ComplexityRoot.NotificationEvent.Number == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.Number(childComplexity), true

	case "NotificationEvent.projectID":
		if e.ComplexityRoot.NotificationEvent.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.ProjectID(childComplexity), true

	case "NotificationEvent.proposalID":
		if e.ComplexityRoot.NotificationEvent.ProposalID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.ProposalID(childComplexity), true

	case "NotificationEvent.read":
		if e.ComplexityRoot.NotificationEvent.Read == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.Read(childComplexity), true

	case "NotificationEvent.taskID":
		if e.ComplexityRoot.NotificationEvent.TaskID == nil {
			break
		}

		return e.ComplexityRoot.NotificationEvent.TaskID(childComplexity), true

	case "NotificationSetting.agentID":
		if e.ComplexityRoot.NotificationSetting.AgentID == nil {
			break
		}

		return e.ComplexityRoot.NotificationSetting.AgentID(childComplexity), true

	case "NotificationSetting.channel":
		if e.ComplexityRoot.NotificationSetting.Channel == nil {
			break
		}

		return e.ComplexityRoot.NotificationSetting.Channel(childComplexity), true

	case "NotificationSetting.enabled":
		if e.ComplexityRoot.NotificationSetting.Enabled == nil {
			break
		}

		return e.ComplexityRoot.NotificationSetting.Enabled(childComplexity), true

	case "NotificationSetting.id":
		if e.ComplexityRoot.NotificationSetting.ID == nil {
			break
		}

		return e.ComplexityRoot.NotificationSetting.ID(childComplexity), true

	case "NotificationSetting.notificationType":
		if e.ComplexityRoot.NotificationSetting.NotificationType == nil {
			break
		}

		return e.ComplexityRoot.NotificationSetting.NotificationType(childComplexity), true

	case "NotificationTypeInfo.description":
		if e.ComplexityRoot.NotificationTypeInfo.Description == nil {
			break
		}

		return e.ComplexityRoot.NotificationTypeInfo.Description(childComplexity), true

	case "NotificationTypeInfo.type":
		if e.ComplexityRoot.NotificationTypeInfo.Type == nil {
			break
		}

		return e.ComplexityRoot.NotificationTypeInfo.Type(childComplexity), true

	case "Project.allowCreatorTransition":
		if e.ComplexityRoot.Project.AllowCreatorTransition == nil {
			break
		}

		return e.ComplexityRoot.Project.AllowCreatorTransition(childComplexity), true

	case "Project.createdAt":
		if e.ComplexityRoot.Project.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Project.CreatedAt(childComplexity), true

	case "Project.description":
		if e.ComplexityRoot.Project.Description == nil {
			break
		}

		return e.ComplexityRoot.Project.Description(childComplexity), true

	case "Project.id":
		if e.ComplexityRoot.Project.ID == nil {
			break
		}

		return e.ComplexityRoot.Project.ID(childComplexity), true

	case "Project.labels":
		if e.ComplexityRoot.Project.Labels == nil {
			break
		}

		return e.ComplexityRoot.Project.Labels(childComplexity), true

	case "Project.members":
		if e.ComplexityRoot.Project.Members == nil {
			break
		}

		return e.ComplexityRoot.Project.Members(childComplexity), true

	case "Project.milestones":
		if e.ComplexityRoot.Project.Milestones == nil {
			break
		}

		return e.ComplexityRoot.Project.Milestones(childComplexity), true

	case "Project.name":
		if e.ComplexityRoot.Project.Name == nil {
			break
		}

		return e.ComplexityRoot.Project.Name(childComplexity), true

	case "Project.number":
		if e.ComplexityRoot.Project.Number == nil {
			break
		}

		return e.ComplexityRoot.Project.Number(childComplexity), true

	case "Project.requireCreatorCloseApproval":
		if e.ComplexityRoot.Project.RequireCreatorCloseApproval == nil {
			break
		}

		return e.ComplexityRoot.Project.RequireCreatorCloseApproval(childComplexity), true

	case "Project.updatedAt":
		if e.ComplexityRoot.Project.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Project.UpdatedAt(childComplexity), true

	case "ProjectMember.agent":
		if e.ComplexityRoot.ProjectMember.Agent == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.Agent(childComplexity), true

	case "ProjectMember.agentID":
		if e.ComplexityRoot.ProjectMember.AgentID == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.AgentID(childComplexity), true

	case "ProjectMember.id":
		if e.ComplexityRoot.ProjectMember.ID == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.ID(childComplexity), true

	case "ProjectMember.number":
		if e.ComplexityRoot.ProjectMember.Number == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.Number(childComplexity), true

	case "ProjectMember.projectID":
		if e.ComplexityRoot.ProjectMember.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.ProjectID(childComplexity), true

	case "ProjectMember.role":
		if e.ComplexityRoot.ProjectMember.Role == nil {
			break
		}

		return e.ComplexityRoot.ProjectMember.Role(childComplexity), true

	case "Proposal.approvedAt":
		if e.ComplexityRoot.Proposal.ApprovedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ApprovedAt(childComplexity), true

	case "Proposal.author":
		if e.ComplexityRoot.Proposal.Author == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Author(childComplexity), true

	case "Proposal.authorID":
		if e.ComplexityRoot.Proposal.AuthorID == nil {
			break
		}

		return e.ComplexityRoot.Proposal.AuthorID(childComplexity), true

	case "Proposal.cancelledAt":
		if e.ComplexityRoot.Proposal.CancelledAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.CancelledAt(childComplexity), true

	case "Proposal.comments":
		if e.ComplexityRoot.Proposal.Comments == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Comments(childComplexity), true

	case "Proposal.completedAt":
		if e.ComplexityRoot.Proposal.CompletedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.CompletedAt(childComplexity), true

	case "Proposal.createdAt":
		if e.ComplexityRoot.Proposal.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.CreatedAt(childComplexity), true

	case "Proposal.description":
		if e.ComplexityRoot.Proposal.Description == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Description(childComplexity), true

	case "Proposal.id":
		if e.ComplexityRoot.Proposal.ID == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ID(childComplexity), true

	case "Proposal.labels":
		if e.ComplexityRoot.Proposal.Labels == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Labels(childComplexity), true

	case "Proposal.number":
		if e.ComplexityRoot.Proposal.Number == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Number(childComplexity), true

	case "Proposal.priority":
		if e.ComplexityRoot.Proposal.Priority == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Priority(childComplexity), true

	case "Proposal.projectID":
		if e.ComplexityRoot.Proposal.ProjectID == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ProjectID(childComplexity), true

	case "Proposal.reviewNote":
		if e.ComplexityRoot.Proposal.ReviewNote == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ReviewNote(childComplexity), true

	case "Proposal.reviewedAt":
		if e.ComplexityRoot.Proposal.ReviewedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ReviewedAt(childComplexity), true

	case "Proposal.reviewer":
		if e.ComplexityRoot.Proposal.Reviewer == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Reviewer(childComplexity), true

	case "Proposal.reviewerID":
		if e.ComplexityRoot.Proposal.ReviewerID == nil {
			break
		}

		return e.ComplexityRoot.Proposal.ReviewerID(childComplexity), true

	case "Proposal.startedAt":
		if e.ComplexityRoot.Proposal.StartedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.StartedAt(childComplexity), true

	case "Proposal.state":
		if e.ComplexityRoot.Proposal.State == nil {
			break
		}

		return e.ComplexityRoot.Proposal.State(childComplexity), true

	case "Proposal.submittedAt":
		if e.ComplexityRoot.Proposal.SubmittedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.SubmittedAt(childComplexity), true

	case "Proposal.tasks":
		if e.ComplexityRoot.Proposal.Tasks == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Tasks(childComplexity), true

	case "Proposal.title":
		if e.ComplexityRoot.Proposal.Title == nil {
			break
		}

		return e.ComplexityRoot.Proposal.Title(childComplexity), true

	case "Proposal.updatedAt":
		if e.ComplexityRoot.Proposal.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Proposal.UpdatedAt(childComplexity), true

	case "ProposalConnection.edges":
		if e.ComplexityRoot.ProposalConnection.Edges == nil {
			break
		}

		return e.ComplexityRoot.ProposalConnection.Edges(childComplexity), true

	case "ProposalConnection.total":
		if e.ComplexityRoot.ProposalConnection.Total == nil {
			break
		}

		return e.ComplexityRoot.ProposalConnection.Total(childComplexity), true

	case "Query.agent":
		if e.ComplexityRoot.Query.Agent == nil {
			break
		}

		args, err := ec.field_Query_agent_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Agent(childComplexity, args["id"].(string)), true

	case "Query.agents":
		if e.ComplexityRoot.Query.Agents == nil {
			break
		}

		args, err := ec.field_Query_agents_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Agents(childComplexity, args["kind"].(*AgentKind), args["status"].(*AgentStatus), args["capabilities"].([]string), args["projectID"].(*string)), true

	case "Query.allowHumanRegistration":
		if e.ComplexityRoot.Query.AllowHumanRegistration == nil {
			break
		}

		return e.ComplexityRoot.Query.AllowHumanRegistration(childComplexity), true

	case "Query.comments":
		if e.ComplexityRoot.Query.Comments == nil {
			break
		}

		args, err := ec.field_Query_comments_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Comments(childComplexity, args["issueID"].(*string), args["proposalID"].(*string), args["taskID"].(*string)), true

	case "Query.commonDeviceInfo":
		if e.ComplexityRoot.Query.CommonDeviceInfo == nil {
			break
		}

		return e.ComplexityRoot.Query.CommonDeviceInfo(childComplexity), true

	case "Query.feedback":
		if e.ComplexityRoot.Query.Feedback == nil {
			break
		}

		args, err := ec.field_Query_feedback_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Feedback(childComplexity, args["targetType"].(FeedbackTargetType), args["targetID"].(string)), true

	case "Query.issue":
		if e.ComplexityRoot.Query.Issue == nil {
			break
		}

		args, err := ec.field_Query_issue_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Issue(childComplexity, args["id"].(string)), true

	case "Query.issues":
		if e.ComplexityRoot.Query.Issues == nil {
			break
		}

		args, err := ec.field_Query_issues_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Issues(childComplexity, args["projectID"].(string), args["state"].(*IssueState), args["states"].([]IssueState), args["priority"].(*Priority), args["assigneeID"].(*string), args["labelIDs"].([]string), args["search"].(*string), args["limit"].(*int32), args["offset"].(*int32)), true

	case "Query.labels":
		if e.ComplexityRoot.Query.Labels == nil {
			break
		}

		args, err := ec.field_Query_labels_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Labels(childComplexity, args["projectID"].(string), args["group"].(*string)), true

	case "Query.milestones":
		if e.ComplexityRoot.Query.Milestones == nil {
			break
		}

		args, err := ec.field_Query_milestones_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Milestones(childComplexity, args["projectID"].(string), args["state"].(*MilestoneState)), true

	case "Query.notificationSettings":
		if e.ComplexityRoot.Query.NotificationSettings == nil {
			break
		}

		args, err := ec.field_Query_notificationSettings_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.NotificationSettings(childComplexity, args["agentID"].(string)), true

	case "Query.notificationTypes":
		if e.ComplexityRoot.Query.NotificationTypes == nil {
			break
		}

		return e.ComplexityRoot.Query.NotificationTypes(childComplexity), true

	case "Query.notifications":
		if e.ComplexityRoot.Query.Notifications == nil {
			break
		}

		args, err := ec.field_Query_notifications_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Notifications(childComplexity, args["agentID"].(string)), true

	case "Query.project":
		if e.ComplexityRoot.Query.Project == nil {
			break
		}

		args, err := ec.field_Query_project_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Project(childComplexity, args["id"].(string)), true

	case "Query.projects":
		if e.ComplexityRoot.Query.Projects == nil {
			break
		}

		return e.ComplexityRoot.Query.Projects(childComplexity), true

	case "Query.proposal":
		if e.ComplexityRoot.Query.Proposal == nil {
			break
		}

		args, err := ec.field_Query_proposal_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Proposal(childComplexity, args["id"].(string)), true

	case "Query.proposals":
		if e.ComplexityRoot.Query.Proposals == nil {
			break
		}

		args, err := ec.field_Query_proposals_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Proposals(childComplexity, args["projectID"].(string), args["state"].(*ProposalState), args["priority"].(*Priority), args["search"].(*string), args["limit"].(*int32), args["offset"].(*int32)), true

	case "Query.supportedModels":
		if e.ComplexityRoot.Query.SupportedModels == nil {
			break
		}

		return e.ComplexityRoot.Query.SupportedModels(childComplexity), true

	case "Query.task":
		if e.ComplexityRoot.Query.Task == nil {
			break
		}

		args, err := ec.field_Query_task_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Task(childComplexity, args["id"].(string)), true

	case "Query.tasks":
		if e.ComplexityRoot.Query.Tasks == nil {
			break
		}

		args, err := ec.field_Query_tasks_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Tasks(childComplexity, args["proposalID"].(string), args["state"].(*TaskState), args["assigneeID"].(*string), args["search"].(*string), args["limit"].(*int32), args["offset"].(*int32)), true

	case "Query.timeline":
		if e.ComplexityRoot.Query.Timeline == nil {
			break
		}

		args, err := ec.field_Query_timeline_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Timeline(childComplexity, args["issueID"].(*string), args["proposalID"].(*string), args["taskID"].(*string)), true

	case "Query.validProposalTransitions":
		if e.ComplexityRoot.Query.ValidProposalTransitions == nil {
			break
		}

		args, err := ec.field_Query_validProposalTransitions_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.ValidProposalTransitions(childComplexity, args["state"].(ProposalState)), true

	case "Query.validTaskTransitions":
		if e.ComplexityRoot.Query.ValidTaskTransitions == nil {
			break
		}

		args, err := ec.field_Query_validTaskTransitions_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.ValidTaskTransitions(childComplexity, args["state"].(TaskState)), true

	case "Query.validTransitions":
		if e.ComplexityRoot.Query.ValidTransitions == nil {
			break
		}

		args, err := ec.field_Query_validTransitions_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.ValidTransitions(childComplexity, args["state"].(IssueState)), true

	case "RegisterResult.agent":
		if e.ComplexityRoot.RegisterResult.Agent == nil {
			break
		}

		return e.ComplexityRoot.RegisterResult.Agent(childComplexity), true

	case "RegisterResult.token":
		if e.ComplexityRoot.RegisterResult.Token == nil {
			break
		}

		return e.ComplexityRoot.RegisterResult.Token(childComplexity), true

	case "Subscription.agentNotifications":
		if e.ComplexityRoot.Subscription.AgentNotifications == nil {
			break
		}

		args, err := ec.field_Subscription_agentNotifications_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Subscription.AgentNotifications(childComplexity, args["agentID"].(string)), true

	case "Subscription.agentStatusChanged":
		if e.ComplexityRoot.Subscription.AgentStatusChanged == nil {
			break
		}

		return e.ComplexityRoot.Subscription.AgentStatusChanged(childComplexity), true

	case "Subscription.issueUpdated":
		if e.ComplexityRoot.Subscription.IssueUpdated == nil {
			break
		}

		args, err := ec.field_Subscription_issueUpdated_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Subscription.IssueUpdated(childComplexity, args["issueID"].(string)), true

	case "Task.assignee":
		if e.ComplexityRoot.Task.Assignee == nil {
			break
		}

		return e.ComplexityRoot.Task.Assignee(childComplexity), true

	case "Task.assigneeID":
		if e.ComplexityRoot.Task.AssigneeID == nil {
			break
		}

		return e.ComplexityRoot.Task.AssigneeID(childComplexity), true

	case "Task.comments":
		if e.ComplexityRoot.Task.Comments == nil {
			break
		}

		return e.ComplexityRoot.Task.Comments(childComplexity), true

	case "Task.completedAt":
		if e.ComplexityRoot.Task.CompletedAt == nil {
			break
		}

		return e.ComplexityRoot.Task.CompletedAt(childComplexity), true

	case "Task.createdAt":
		if e.ComplexityRoot.Task.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Task.CreatedAt(childComplexity), true

	case "Task.description":
		if e.ComplexityRoot.Task.Description == nil {
			break
		}

		return e.ComplexityRoot.Task.Description(childComplexity), true

	case "Task.id":
		if e.ComplexityRoot.Task.ID == nil {
			break
		}

		return e.ComplexityRoot.Task.ID(childComplexity), true

	case "Task.issues":
		if e.ComplexityRoot.Task.Issues == nil {
			break
		}

		return e.ComplexityRoot.Task.Issues(childComplexity), true

	case "Task.number":
		if e.ComplexityRoot.Task.Number == nil {
			break
		}

		return e.ComplexityRoot.Task.Number(childComplexity), true

	case "Task.priority":
		if e.ComplexityRoot.Task.Priority == nil {
			break
		}

		return e.ComplexityRoot.Task.Priority(childComplexity), true

	case "Task.proposal":
		if e.ComplexityRoot.Task.Proposal == nil {
			break
		}

		return e.ComplexityRoot.Task.Proposal(childComplexity), true

	case "Task.proposalID":
		if e.ComplexityRoot.Task.ProposalID == nil {
			break
		}

		return e.ComplexityRoot.Task.ProposalID(childComplexity), true

	case "Task.startedAt":
		if e.ComplexityRoot.Task.StartedAt == nil {
			break
		}

		return e.ComplexityRoot.Task.StartedAt(childComplexity), true

	case "Task.state":
		if e.ComplexityRoot.Task.State == nil {
			break
		}

		return e.ComplexityRoot.Task.State(childComplexity), true

	case "Task.title":
		if e.ComplexityRoot.Task.Title == nil {
			break
		}

		return e.ComplexityRoot.Task.Title(childComplexity), true

	case "Task.updatedAt":
		if e.ComplexityRoot.Task.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Task.UpdatedAt(childComplexity), true

	case "TaskConnection.edges":
		if e.ComplexityRoot.TaskConnection.Edges == nil {
			break
		}

		return e.ComplexityRoot.TaskConnection.Edges(childComplexity), true

	case "TaskConnection.total":
		if e.ComplexityRoot.TaskConnection.Total == nil {
			break
		}

		return e.ComplexityRoot.TaskConnection.Total(childComplexity), true

	case "TimelineEvent.actor":
		if e.ComplexityRoot.TimelineEvent.Actor == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.Actor(childComplexity), true

	case "TimelineEvent.actorID":
		if e.ComplexityRoot.TimelineEvent.ActorID == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.ActorID(childComplexity), true

	case "TimelineEvent.createdAt":
		if e.ComplexityRoot.TimelineEvent.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.CreatedAt(childComplexity), true

	case "TimelineEvent.eventType":
		if e.ComplexityRoot.TimelineEvent.EventType == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.EventType(childComplexity), true

	case "TimelineEvent.id":
		if e.ComplexityRoot.TimelineEvent.ID == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.ID(childComplexity), true

	case "TimelineEvent.issueID":
		if e.ComplexityRoot.TimelineEvent.IssueID == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.IssueID(childComplexity), true

	case "TimelineEvent.number":
		if e.ComplexityRoot.TimelineEvent.Number == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.Number(childComplexity), true

	case "TimelineEvent.payload":
		if e.ComplexityRoot.TimelineEvent.Payload == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.Payload(childComplexity), true

	case "TimelineEvent.proposalID":
		if e.ComplexityRoot.TimelineEvent.ProposalID == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.ProposalID(childComplexity), true

	case "TimelineEvent.taskID":
		if e.ComplexityRoot.TimelineEvent.TaskID == nil {
			break
		}

		return e.ComplexityRoot.TimelineEvent.TaskID(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalMap := graphql.BuildUnmarshalerMap()
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}
	case ast.Subscription:
		next := ec._Subscription(ctx, opCtx.Operation.SelectionSet)

		var buf bytes.Buffer
		return func(ctx context.Context) *graphql.Response {
			buf.Reset()
			data := next(ctx)

			if data == nil {
				return nil
			}
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) executionContext {
	return executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

//go:embed "agent.graphqls" "comment.graphqls" "feedback.graphqls" "issue.graphqls" "label.graphqls" "milestone.graphqls" "mutation.graphqls" "notification.graphqls" "project.graphqls" "proposal.graphqls" "query.graphqls" "scalar.graphqls" "subscription.graphqls" "task.graphqls" "timeline.graphqls"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "agent.graphqls", Input: sourceData("agent.graphqls"), BuiltIn: false},
	{Name: "comment.graphqls", Input: sourceData("comment.graphqls"), BuiltIn: false},
	{Name: "feedback.graphqls", Input: sourceData("feedback.graphqls"), BuiltIn: false},
	{Name: "issue.graphqls", Input: sourceData("issue.graphqls"), BuiltIn: false},
	{Name: "label.graphqls", Input: sourceData("label.graphqls"), BuiltIn: false},
	{Name: "milestone.graphqls", Input: sourceData("milestone.graphqls"), BuiltIn: false},
	{Name: "mutation.graphqls", Input: sourceData("mutation.graphqls"), BuiltIn: false},
	{Name: "notification.graphqls", Input: sourceData("notification.graphqls"), BuiltIn: false},
	{Name: "project.graphqls", Input: sourceData("project.graphqls"), BuiltIn: false},
	{Name: "proposal.graphqls", Input: sourceData("proposal.graphqls"), BuiltIn: false},
	{Name: "query.graphqls", Input: sourceData("query.graphqls"), BuiltIn: false},
	{Name: "scalar.graphqls", Input: sourceData("scalar.graphqls"), BuiltIn: false},
	{Name: "subscription.graphqls", Input: sourceData("subscription.graphqls"), BuiltIn: false},
	{Name: "task.graphqls", Input: sourceData("task.graphqls"), BuiltIn: false},
	{Name: "timeline.graphqls", Input: sourceData("timeline.graphqls"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
