package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"chick/internal/events"
	"chick/internal/models"
	"context"
	"fmt"
	"time"
)

// IssueUpdated is the resolver for the issueUpdated field.
func (r *subscriptionResolver) IssueUpdated(ctx context.Context, issueID string) (<-chan *Issue, error) {
	id := parseID(issueID)
	// Verify caller has access to this issue's project
	if _, err := r.requireIssueProjectMember(ctx, id); err != nil {
		return nil, err
	}

	ch := make(chan *Issue, 1)

	// Publish initial state
	issue, err := r.IssueSvc.GetByID(id)
	if err == nil {
		ch <- issueFromModel(issue)
	}

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventIssueStateChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueStateChangedPayload)
			if !ok {
				return
			}
			if payload.IssueID == id {
				issue, err := r.IssueSvc.GetByID(id)
				if err == nil {
					select {
					case ch <- issueFromModel(issue):
					default:
					}
				}
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// AgentNotifications is the resolver for the agentNotifications field.
func (r *subscriptionResolver) AgentNotifications(ctx context.Context, agentID string) (<-chan *NotificationEvent, error) {
	id := parseID(agentID)
	// Verify the caller is requesting their own notifications
	if _, err := requireSelfAccess(ctx, id); err != nil {
		return nil, err
	}

	ch := make(chan *NotificationEvent, 20)

	var cancels []func()
	if r.EventBus != nil {
		cancels = append(cancels, r.EventBus.Subscribe(events.EventIssueAssigneeChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueAssigneeChangedPayload)
			if !ok {
				return
			}
			if payload.AgentID == id {
				msg := "You have been assigned to an issue"
				if payload.Action == "removed" {
					msg = "You have been unassigned from an issue"
				}
				select {
				case ch <- &NotificationEvent{
					ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
					NotificationType: "assignee_changed",
					Message:          msg,
					Read:             false,
					CreatedAt:        time.Now(),
				}:
				default:
				}
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventCommentAdded, func(evt events.Event) {
			_, ok := evt.Payload.(events.CommentAddedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "comment_added",
				Message:          "New comment on an issue",
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventProposalCreated, func(evt events.Event) {
			payload, ok := evt.Payload.(events.ProposalCreatedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "proposal_created",
				Message:          fmt.Sprintf("New proposal #%d created", payload.ProposalID),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventProposalStateChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.ProposalStateChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "proposal_state_changed",
				Message:          fmt.Sprintf("Proposal #%d: %s → %s", payload.ProposalID, payload.From, payload.To),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventTaskCreated, func(evt events.Event) {
			payload, ok := evt.Payload.(events.TaskCreatedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "task_created",
				Message:          fmt.Sprintf("New task #%d created under proposal #%d", payload.TaskID, payload.ProposalID),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventTaskStateChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.TaskStateChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "task_state_changed",
				Message:          fmt.Sprintf("Task #%d: %s → %s", payload.TaskID, payload.From, payload.To),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventAgentStatusChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.AgentStatusChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "agent_status_changed",
				Message:          fmt.Sprintf("Agent #%d is now %s", payload.AgentID, payload.Status),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))

		cancels = append(cancels, r.EventBus.Subscribe(events.EventFeedbackCreated, func(evt events.Event) {
			payload, ok := evt.Payload.(events.FeedbackCreatedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "feedback_received",
				Message:          fmt.Sprintf("New feedback on %s #%d", payload.TargetType, payload.TargetID),
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		}))
	}

	go func() {
		<-ctx.Done()
		for _, c := range cancels {
			c()
		}
		close(ch)
	}()

	return ch, nil
}

// AgentStatusChanged is the resolver for the agentStatusChanged field.
func (r *subscriptionResolver) AgentStatusChanged(ctx context.Context) (<-chan *AgentStatusEvent, error) {
	ch := make(chan *AgentStatusEvent, 5)

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventAgentStatusChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.AgentStatusChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &AgentStatusEvent{
				AgentID:   formatID(payload.AgentID),
				Status:    AgentStatus(models.AgentStatus(payload.Status)),
				Timestamp: time.Now(),
			}:
			default:
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
